### ISSUE TITLE
Limit aws resource with 32 chars

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1133]
'Some resource name (such as: api-int-jenkins-aws-upi-1az-rhel7-3m-3w-tier1) would excceed aws limitation (32), pls adjust your cluster name for a shorter name'\n+ exit 1\n"

See more details here:  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/2838//console

**Comment by gklein** [comment]
This failures is happening at the [upi_on_aws-install.sh expected_infra_name check](http://git.app.eng.bos.redhat.com/git/openshift-misc.git/tree/v3-launch-templates/functionality-testing/aos-4_2/hosts/upi_on_aws-install.sh#n103)

As the "api-int-" prefix takes 8 characters, it means the cluster name max length can be 24 characters in order to satisfy this check.

**Comment by gklein** [comment]
Even if we adapt the cluster name to a maximum of 24 characters, it might fail due the the next  [upi_on_aws-install.sh expected_apps_infra_name check](http://git.app.eng.bos.redhat.com/git/openshift-misc.git/tree/v3-launch-templates/functionality-testing/aos-4_2/hosts/upi_on_aws-install.sh#n108)

Here there are 15 additional characters in the "-xxxxx-int-apps" suffix, which means the cluster name max length can only be 17 characters long in order to satisfy this check.
