### ISSUE TITLE
Deployment prerequisite check should happened before downloading the installer

### ISSUE THREAD

**Issue by gklein** [red-hat-storage/ocs-ci#1195]
Currently, the deployment prerequisites check `deploy_prereq()` is happening after the installer was already downloaded.

In case of a failure in the prerequisites check, It is possible to save a short time and a wasteful download if we move `deploy_prereq()` to run before `download_installer()`.

**Comment by clacroix12** [comment]
I like this idea, however it will require changes on the AWS UPI side. We are [copying the openshift installer to another location](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/aws.py#L346-L356) because of what the shell script we are executing expects. We are doing this inside the `deploy_prereq` method. This won't be an issue once we complete #1025 however right now it is. We can easily move this to the `deploy` method instead as long as it happens before we execute the shell script.
