### ISSUE TITLE
Split mcg_bucket into Object Bucket Claim and Object Bucket

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#1405]
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/resources/mcg_bucket.py implements classes `MCGBucket`, `S3Bucket`, `OCBucket` and `CLIBucket`. These classes are accessing `obc` resources but their names indicate that they represent `ob`. There should be representations for Bucket and Bucket claim. Bucket should contain reference to its bucket claim object.

**Comment by fbalak** [comment]
@MeridianExplorer Do you think that this makes sense?

**Comment by MeridianExplorer** [comment]
Hi @fbalak - thanks for bringing this up!

I believe we actually have a mixed bag over here - 
OCBucket and CLIBucket create an OBC, that in turn creates an OB. The objects they represent are indeed claims, and not the buckets themselves. However, S3Bucket actually represents an object bucket, since S3 is a different control plane that does not use bucket claims.

I believe a possible direction will be to change the CLI and OC buckets to point at their actual object buckets (using S3), and they'll also contain their respective claims, in a different attribute. 

What do you think?

**Comment by fbalak** [comment]
@MeridianExplorer That would be a possible solution but I think that it would be better to have distinct representation for buckets and claims. Do you think it would make sense to have one `ObjectBucketClaim` class with some `method` parameter that takes values `OC` or `CLI`?

Also, we can have `ObjectBucket` objects with link to `ObjectBucketClaim` object that was used to create them and work with them separately so there will be no confusion for user about what resource is currently used.

**Comment by MeridianExplorer** [comment]
@fbalak - OBC was implemented in March - 

https://github.com/red-hat-storage/ocs-ci/blob/bdb4fce13b5582df09afef9028665554151fb307/ocs_ci/ocs/resources/bucket_policy.py#L14-L17

Considering we do not interact with OBs directly - I personally think it's sufficient. What do you think?

**Comment by fbalak** [comment]
If we don't interact with OBs directly then it's probably ok to close it but we should make sure that correct terminology is used everywhere (claims are not referenced as buckets).

**Comment by MeridianExplorer** [comment]
I agree with your point that the terminology is problematic - but refactoring all our code to treat OBCs as OBCs instead of buckets will be a pretty heavy undertaking right now. Maybe we can add some text regarding those terminologies somewhere in OCSCI?
