### ISSUE TITLE
We didn't run must-gather during deployment over VmWare over RHEL nodes

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#1608]
I see that we didn't executed the must-gather when we failed during run some command over RHEL nodes here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/5210//console

For this situation we really need to run must-gather to understand what happened that debug RHEL pod didn't come up .

@dahorak and @shylesh as focal point, can you please take a look at this?

**Comment by dahorak** [comment]
The failed command was from this [workaround](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L903) (PR https://github.com/red-hat-storage/ocs-ci/pull/1180, Issue https://github.com/red-hat-storage/ocs-ci/issues/1151), must-gather for deployment is handled in [`deploy_cluster(..)`](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L74) method, which is called before the workaround (and the workaround is outside of this method).
Also the general must-gather for regular test cases is watching only for failures in [test (not setup/teardown)](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/pytest_customization/ocscilib.py#L333).

The question here is, if the workaround is still needed, since the [BZ 1777384](https://bugzilla.redhat.com/show_bug.cgi?id=1777384) is already closed? (I didn't check it deeply what is the real resolution.)

**Comment by petr-balogh** [comment]
OK, thanks, I did revert here:  https://github.com/red-hat-storage/ocs-ci/pull/1610 and will run test execution.

**Comment by sidhant-agrawal** [comment]
@dahorak @petr-balogh 
Unless I'm missing something we still need this workaround.
This status of [RHSTOR-787](https://issues.redhat.com/browse/RHSTOR-787) is still in `TO DO`

**Comment by petr-balogh** [comment]
Thanks for update @sidhant-agrawal, I moved the WA on different place then to fix this issue.
