### ISSUE TITLE
Move Conf folder under ocs

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#162]

**Comment by vasukulkarni** [comment]
Directory structure fixes: 
 -> ocsci + ocs

**Comment by vasukulkarni** [comment]
move oc -> ocs

**Comment by clacroix12** [comment]
> -> ocsci + ocs

I don't think `ocs` and `ocsci` should be combined necessarily. These are two different things. We may want to change the name of `ocsci` to something like `framework` to avoid confusion, but I wouldn't combine them because they were intended to do different things. `ocs` should be any code that interfaces with the product. `ocsci` is framework level code. In the even that we do consolidate our python modules into a top level directory, I still believe these two should be separate to some degree.

**Comment by clacroix12** [comment]
On the topic of consolidating to `ocs`. Why do we have a separate top level directory for `resources`? This seems like something that should belong under `ocs` as well.

**Comment by mbukatov** [comment]
Directory `conf` will remain in the root directory, as discussed in hierarchy clarification issue https://github.com/red-hat-storage/ocs-ci/issues/207, which discusses structure of whole repository.
