### ISSUE TITLE
Clusters brought up by PR validation job should not be long living by default

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#1813]
## The problem:
In case a PR validation job is aborted, the cluster has to be destroyed. This leads to clusters in AWS  that were brought up by PR validation job, to stay running for 36 hours, which is the default time for ec2 instances brought up by Jenkins, before they are being deleted by our aws-cleanup.

## Proposed solution:
By default, the running time of clusters brought by PR validation job should be shorter, like 6-10 hours. We can have a parameter in the PR validation job that allows specifying the allowed running time to be longer. This could be used for PRs that their validation requires long running clusters.

**Comment by RazTamir** [comment]
We can also remove the option to abort a verification job

**Comment by ebenahar** [comment]
Another option - if possible, abort should trigger destroy job

**Comment by clacroix12** [comment]
> We can also remove the option to abort a verification job

I don't know if this is the right option since we might need to abort for a good reason, i.e. the job is stuck for several hours with no signs of continuing on.

> Another option - if possible, abort should trigger destroy job

I feel like abort should do what it does which is to "just stop." Once we start hooking other behavior on top of abort it becomes this other caveat that we need to consider.

I like the proposed solution which is to use (by default) a shorter lived cluster prefix specifically for PR test clusters with the ability to pass a different cluster prefix for jobs that require additional time. This is obviously a bit more complex but in my opinion a much more elegant solution.

**Comment by ebenahar** [comment]
> I like the proposed solution which is to use (by default) a shorter lived cluster prefix specifically for PR test clusters with the ability to pass a different cluster prefix for jobs that require additional time. This is obviously a bit more complex but in my opinion a much more elegant solution.

+1. I guess this means that instances brought up by PR validation will not have 'jnk' in their name as this will collide with the prefix of instances brought up by other Jenkins jobs

**Comment by petr-balogh** [comment]
IIRC and you click abort on the PR verification job I think that underlaying deploy job is constructed like it should try to run destroy job. But If it's forcibly aborted (If you click multiple times on abort button) then it will not continue with abort of course.  And as Coady told, there might be a lot of good reasons why we would like to abort job. For example if you passed wrong params and realized just after executed job.
