### ISSUE TITLE
test_nodereplacement_proactive failes with HEALTH_WARN 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#1821]
Ceph cluster health is not OK. Health: {health}"
            )
E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; Degraded data redundancy: 8285/204969 objects degraded (4.042%), 42 pgs degraded, 42 pgs undersized

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7051/295489/295511/295512/log
Run ID: 1670222569
Test Case: test_nodereplacement_proactive
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS LOWERREQ VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6298/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthulwreq-t4a/vavuthulwreq-t4a_20221205T051247/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum a,c; 1 osds down; 1 host (1 osds) down; 1 rack (1 osds) down; Degraded data redundancy: 861/2583 objects degraded (33.333%), 133 pgs degraded, 353 pgs undersized"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6990/291234/291257/291259/log
Run ID: 1670003634
Test Case: test_nodereplacement_twice
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS LOWERREQ VMFS 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6291/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-006vu1clqv33-t4a/j-006vu1clqv33-t4a_20221202T155738/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum b,d; 1 osds down; 1 host (1 osds) down; 1 rack (1 osds) down; Degraded data redundancy: 1350/4050 objects degraded (33.333%), 131 pgs degraded, 353 pgs undersized"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6956/290001/290022/290024/log
Run ID: 1669974824
Test Case: test_nodereplacement_proactive
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 2+arbiter AZ RHCOS LSO VMDK ARBITER 3M 6W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6279/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-034vu2clva36-t4a/j-034vu2clva36-t4a_20221202T083438/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 2 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 1 host (2 osds) down; Degraded data redundancy: 714/3596 objects degraded (19.855%), 177 pgs degraded, 341 pgs undersized"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6640/272924/272990/272991/log
Run ID: 1669612560
Test Case: test_rolling_terminate_and_recovery_in_controlled_fashion_ipi
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 IPI 1AZ RHCOS VSAN 3M 3W tier4b
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6147/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-026vi1cs33-t4b/j-026vi1cs33-t4b_20221128T040824/logs/
Error Message: ```ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum b,c; 2 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 2 hosts (2 osds) down; 1 rack (2 osds) down; Degraded data redundancy: 1508/4524 objects degraded (33.333%), 150 pgs degraded, 353 pgs undersized```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6596/271263/271289/271291/log
Run ID: 1669404527
Test Case: test_nodereplacement_proactive
ODF Build: 4.12.0-116
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6134/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t4a/j-001vud1cs33-t4a_20221125T174052/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum b,c; 1 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 1 host (1 osds) down; 1 rack (1 osds) down; Degraded data redundancy: 833/2499 objects degraded (33.333%), 130 pgs degraded, 353 pgs undersized"```

**Comment by am-agrawa** [comment]
@prsurve Do we have any open PR to address this issue?

**Comment by ebenahar** [comment]
Reported https://github.com/red-hat-storage/ocs-ci/issues/7390 for tracking the failures with 
```
HEALTH_WARN 1/3 mons down, quorum a,c; 1 osds down; 1 host (1 osds) down; 1 rack (1 osds) down
```
