### ISSUE TITLE
Remove the 'cluster name' text input for jenkins deployment job

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1974]
We require 'cluster name' input in deployment job but essentially has to be username of the jenkins or else the job will fail.

Since that is a hard requirement, we can very well fix the username to be jenkins username and disable that for fresh job.

**Comment by clacroix12** [comment]
I don't think we should remove it entirely as it's necessary for our trigger jobs to pass it to the deploy job. We might be able to do something like "default" it to the current users username though? I'd need @dahorak or @petr-balogh to weigh on on that one though as I'm not certain we can do that, I'm just thinking of alternatives.

**Comment by vasukulkarni** [comment]
*default* sounds good option as well.

**Comment by dahorak** [comment]
I'm not sure if I understand this ticket correctly (and mainly the reason for it), but this is not exactly true:
> We require 'cluster name' input in deployment job but essentially has to be username of the jenkins or else the job will fail.

The `CLUSTER_NAME` can be any string from letters, digits and dash (`-`) 5 - 17 characters long. If the job is directly triggered by user (not via any subsequent job), the `CLUSTER_NAME` parameter also have to **contain** username of the user.

For example following names are completely valid:
`dahorak-cluster01`,
`dahorak-test`,
even `aws-dahorak` (but I would say that good habit is to start with the username).

It is good idea, to pre-configure user's name as default value to the `CLUSTER_NAME` field, but I'm afraid that it is not easily possible (but maybe I'm wrong, it is definitely worth to check it).
From my point of view, it has to be really set directly in the job _Build with Parameters_ form (not just replacing some placeholder string in the pipeline code after the job is triggered, because in that case user will not known what is the final name of his/her cluster - printing it to the console output is not enough to make it clear)).

**Comment by petr-balogh** [comment]
I am and others using the CLUSTER_NAME a lot to add some additional info to the cluster name like `pbalogh-upgrade` so this cluster I am using now for upgrade testing. Other I see that the cluster name is used a lot that people adding where the cluster is created like `pbalogh-vmware`, `pbalogh-aws` or `pbalogh-dc25` so I don't think we should delete this and also it allows users to have multiple clusters in the jenkins.

I can imagine like that if CLUSTER_NAME will be empty string so user will not pass any value than in the pipeline we can take user's kerberos login as default value. This is what @clacroix12 meant I guess.  @dahorak no need to have this value written in the cluster name. Just if not specified we will use kerberos ID.  This we can easily do.

**Comment by dahorak** [comment]
> I can imagine like that if CLUSTER_NAME will be empty string so user will not pass any value than in the pipeline we can take user's kerberos login as default value. This is what @clacroix12 meant I guess. @dahorak no need to have this value written in the cluster name. Just if not specified we will use kerberos ID. This we can easily do.

I have concern about this behaviour - as mentioned in my previous comment - that user will build cluster without knowing/noticing the cluster name...

**Comment by petr-balogh** [comment]
if this will be described as default behavior then they will know that their cluster name is always their kerberos ID as default. So they will know that cluster_name = kerberos id if not specified ?

**Comment by dahorak** [comment]
Yeah.. I know... but how often were suggesting/mentioning/describing not to rebuild the deploy job, use kerberos id in cluster name (before it was forced in the job logic), properly cleanup their clusters or similar suggestions/rules and still there were number of "violations" of those rules.

Anyway my point of view is, that it is not too much annoying to fill the CLUSTER_NAME manually (keep the current behaviour), but on the other side, I don't have any big problem with implementing the default to be the kerberos id as you mentioned.

**Comment by jimdevops19** [comment]
Should we implement this?
If I think of a scenario where the user missed a letter of his username, "dahork", instead of "dahorak",

Then we should correct the entire Cluster Name ?  So the result would be: dahorak-$(some_correction)

Or just concatenating the actual KerberosID with the specified name?
But then the result could look like: "dahorak-dahork" which makes it a little long and not nice.

**Comment by dahorak** [comment]
I think, that if user provide any cluster name and the provided cluster name doesn't comply with the existing rules (e.g. it doesn't contain kerberos id or contain forbidden characters) - no matter if it is because of typo or not, the job should be aborted with proper error message - which is current behaviour.

**Comment by dahorak** [comment]
There is no update for nearly 1 year and people are familiar with the current behavior of the `CLUSTER_NAME` parameter, so I think we can close this ticket.
