### ISSUE TITLE
Organize fixtures in a conventionalized way

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#200]
We should agree on a standard of where to put fixtures implementation. 
Currently, we have fixtures written in different places - [inside the test file](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/test_add_mds_to_cluster.py#L21), [in conftest.py](https://github.com/red-hat-storage/ocs-ci/pull/98/files#diff-484462fced51d1a06b1d93b4a44dd535R1) and [in fixtures.py ](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/fixtures.py).

**Comment by mbukatov** [comment]
I would say that having some [fixtures](https://docs.pytest.org/en/latest/fixture.html) in test files and others in conftest.py files doesn't constitute a conflict or breach on standard pytest conventions.

It makes sense to keep fixtures which automates specific setup for small number of test cases (as present in a particular python file) in the test file, while moving the fixture into conftest makes it usable for wider number of tests, and so this makes sense for more general setup/teardown.

I'm against keeping fixtures in fixtures.py files, as it conflicts with standard pytest conventions, and creates additional layer on top of pytest for no good reason. Also both people new to pytest and experienced pytest users will find it weird (both will get into question why we are using fixtures in a different way compared to all documentation related to pytest found on the internet).

**Comment by ebenahar** [comment]
Thanks @mbukatov, sounds good to me. Replaced fixtures.py with conftest.py - https://github.com/red-hat-storage/ocs-ci/pull/203

**Comment by mbukatov** [comment]
Summary based on:

 * https://github.com/red-hat-storage/ocs-ci/pull/237#discussion_r294360820
 * https://github.com/red-hat-storage/ocs-ci/pull/237#issuecomment-502802865

## Description

Instead of referencing fixtures via direct reference like this:

```
from somewhere import setup_something

@pytest.mark.usefixtures(  # noqa: F405
    setup_something.__name__,
    ...
```

let's use [canonical pytest way of using fixtures](https://docs.pytest.org/en/latest/fixture.html), placing fixture into conftest.py file or in python file with the test (as noted above, this depends on expected reusability of the fixture):

```
@pytest.mark.usefixtures("setup_something")
class SomeTest():
    ...
```

or (for test functions or methods):

```
def test_something(setup_something):
    ...
```

**Comment by mbukatov** [comment]
I don't think this was addressed (eg. there still is `tests/fixtures.py` file).
