### ISSUE TITLE
Don't use Ingress certificate for external MCG communications when running on IBM Cloud

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#2454]
The default root certificates are sufficient. The Ingress cert leads to a verification failure.

**Comment by fbalak** [comment]
@MeridianExplorer I am reopening this issue because tests run in IBM Cloud are now failing on SSL error and in PR https://github.com/red-hat-storage/ocs-ci/pull/2684 you wrote into description that it reverts changes done in PR https://github.com/red-hat-storage/ocs-ci/pull/2442 linked to this issue as fix.

```
>               raise SSLError(e, request=request)
E               requests.exceptions.SSLError: HTTPSConnectionPool(host='noobaa-mgmt-openshift-storage.newsdscluster001-5618d9f71a0fba583604<some url>', port=443): Max retries exceeded with url: /rpc (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))
```
