### ISSUE TITLE
AWS UPI add node probably creates stack with None-noX and is not cleaned up

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2550]
<img width="1084" alt="Screen Shot 2020-07-22 at 11 09 58 AM" src="https://user-images.githubusercontent.com/16169617/88158083-e2ccca80-cc0b-11ea-8296-5955bdf9df97.png">

I see we have a lot of resources leftovers in cloudformation stack with name None-noX .

We probably have some BZ that we don't expand the proper name of cluster and have None instead.

This has to be fixed.

@clacroix12  when you will deal with other issue, can you please take a look at this as well?
Thanks

**Comment by petr-balogh** [comment]
https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/parameters?filteringText=&filteringStatus=active&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aus-east-2%3A861790564636%3Astack%2FNone-no5%2F40d51eb0-90e9-11ea-b2f5-0653eeca5e60

Here I can see for example 

WorkerInstanceProfileName | sshreeka-awstwo-vb5v6-worker-profile

So I my guess is that we are taking some value using .get somewhere and as this value is missing we get default None here but didn't do proper code examination yet.

@shreekarSS  are you aware of this? As it's happened a lot of with your name in cluster name?

**Comment by clacroix12** [comment]
I had a conversation with @shylesh about this and I'm pretty sure we know what's going on. I'm going to try to reproduce it but our thought is that these test executions are happening without providing a cluster name. We enforce the `--cluster-name` parameter when we are executing deployments but not when we are simply running tests. `test_node_expansion` is being run without providing a cluster name and when we get to [here](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/aws.py#L892) we are trying to determine the `worker_pattern`. This pattern is being used to determine what we can logically use as a name for this cloudformation stack. Since the execution is not being run with a cluster name, the default value for `cluster_name` is being used (`null`) and pattern we get is `None-no[0-9]+`. Also, since these stacks don't match the actual cluster name, they are not being cleaned up during teardown so they remain in cloudformation forever.

We have a couple of options here regarding fixes:

- We can simply raise an error if we get a `cluster_name` of `None` before using that in the worker pattern.
- We can enforce the usage of `--cluster-name` for test executions that run test expansion
- We can read in the cluster name (infra-id) from the metadata.json file instead of from the config
- We can ensure that the cluster_name value in the config is updated via the metadata.json file in the case where we don't provide a `--cluster-name`

For now I'm going to try to reproduce this issue to verify our assumptions here. I'd like some input around what kind of solution we want to go with here.

@petr-balogh @shreekarSS

**Comment by clacroix12** [comment]
I've confirmed that this is the pattern that is constructed when a `test_node_expansion` test run is executed without passing a cluster name:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/clacroix/workspace/ocs-ci/ocs_ci/utility/aws.py(895)get_worker_stacks()
-> return self.get_matching_stacks(worker_pattern)
(Pdb) worker_pattern
'None-no[0-9]+'
(Pdb)
```

I've also confirmed that the cloudformation stack is created (in my case `None-no19`) using this pattern, successfully reproducing the issue.

**Comment by petr-balogh** [comment]
```{"clusterName":"jnk-pr2518-b2404","clusterID":"1c293975-e9eb-4975-8110-8441aee39b35","infraID":"jnk-pr2518-b2404-jprxx","aws":{"region":"us-east-2","identifier":[{"kubernetes.io/cluster/jnk-pr2518-b2404-jprxx":"owned"},{"openshiftClusterID":"1c293975-e9eb-4975-8110-8441aee39b35"}]}}```

This is some random metadata.json file I found in one of the job. 

We can use dirctly clusterName or infraID, I don't mind, just not sure if there is some limit in the name in stack? Or do we already deal with this in the code somewhere?

We can go with dynamic update of config @clacroix12 , just make sure that if metadata.json file does not exists (ROKS env), or if someone have just kubeconfig file we cannot fail this config update. And if we will not fail it we will hit the same issue here.

So I would go to try update from metadata, json file - But our cluster name is `clusterName` and not infraID right?
In case we don't have metadata.json file then raise the exception that if no metadata.json file exists, the --cluster-name parameter is mandatory.

WDYT?

**Comment by clacroix12** [comment]
> So I would go to try update from metadata, json file - But our cluster name is clusterName and not infraID right?

This is correct, yeah. We would update the config with `clusterName` not `infraID`

> In case we don't have metadata.json file then raise the exception that if no metadata.json file exists, the --cluster-name parameter is mandatory.

+1
