### ISSUE TITLE
Change default LSO namespace from local-storage to openshift-local-storage to align with OCS 4.6

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2640]
LSO changed suggested default namespace from `local-storage` to `openshift-local-storage`, see https://github.com/openshift/local-storage-operator/pull/127. Moreover the namespace has been specified as suggested default namespace for the LSO operator, so that users don't have to create it themselves anymore.

We need to do matching changes since OCS 4.6.

**Comment by clacroix12** [comment]
Currently the LSO namespace is specified in our constants module. Since this is no longer a constant, I suggest that we move the definition to our default config and update the value in our config during LSO depoyment based on OCP version if necessary. This way we can ensure that all uses of this namespace are pulling from the same place while ensuring it is correct for OCP 4.6 and beyond.

Once we no longer need to support the OCP < 4.6 use case (`local-storage`) we can move back it back to constants if that is preferred.

**Comment by clacroix12** [comment]
I tested an LSO deployment on OCP 4.5 with the new namespace (`openshift-local-storage`) and the deployment was successful. Assuming anything that uses/references the local storage namespace does so through the constant we have defined I think it's safe to use the new namespace for all OCP versions.

**Comment by mbukatov** [comment]
I agree that we can just rename the default namespace from `local-storage` to `openshift-local-storage`.

Strictly speaking,we should use `local-storage` as a default namespace for OCP < 4.6 because that is what the documentation states. There are also few subtle differences in handling `openshift-` prefixed namespaces. But since our testing with OCP < 4.6 is already done, and there is no observable difference between these 2 namespace names, there is no point in trying to preserve `local-storage` namespace usage for < 4.6 test runs.
