### ISSUE TITLE
Handling existing cluster outside qe

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2704]
We have seen couple of issues that needs to be addressed when existing cluster is used from outside qe 

1) Download of oc binary in bin/folder if not already present
2) Dont bailout on report version checks in operators and catalog namespace
   ex:

"""
-OPERATOR_CATALOG_SOURCE_NAME = "ocs-catalogsource"
+OPERATOR_CATALOG_SOURCE_NAME = "redhat-operators"
$ oc -n openshift-marketplace --kubeconfig /Users/kylebader/src/infra-nodes/kb/auth/kubeconfig get CatalogSource ocs-catalogsource -n openshift-marketplace -o yaml
Error from server (NotFound): catalogsources.operators.coreos.com "ocs-catalogsource" not found
"""

3) cluster-name should not be mandatory

4) mcg tests loads s3 config in pytest customization - add exception checks

**Comment by vasukulkarni** [comment]
5.
```
Kyles-Mac-mini:ocs-ci kylebader$ run-ci -m "test" --cluster-name kb --cluster-path ~/src/infra-nodes/kb tests/libtest/test_pod_exec.py
Collecting Cluster versions
Problem occurred when looking for some resource! Error: Requested packageManifest: ocs-operator with selector: ocs-operator-internal=true not found!
Failed to gather version details! The report of version mightnot be complete!
======================================================= test session starts ========================================================
platform darwin -- Python 3.7.7, pytest-5.3.5, py-1.9.0, pluggy-0.13.1
rootdir: /Users/kylebader/src/ocs-ci, inifile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, ordering-0.6, logger-0.5.1, reportportal-1.10.0, marker-bugzilla-0.9.4
collected 1 item / 1 deselected
```

**Comment by clacroix12** [comment]
@vasukulkarni I'm wondering if #2562 is what is being hit here.

**Comment by vasukulkarni** [comment]
> > 1. cluster-name should not be mandatory
> 
> @vasukulkarni I'm wondering if #2562 is what is being hit here.

That is the one!!

**Comment by clacroix12** [comment]
This is to be expected then. Essentially what is happening is that the user is specifying a `cluster_path` that does not have a `metadata.json` file to pull the cluster name from. Since we can't determine what the cluster name is from the provided `cluster_path`, the user will need to specify the cluster name with `--cluster-name`. Normally, if the cluster is in a *good* state the `metadata.json` file will exist so this shouldn't happen on every execution. 

The reason this check is necessary is because we were executing certain tests (cluster expansion) without a cluster name and it was having adverse effects when creating things like cloudformation stacks. As such we attempt to pull the `cluster_name` from `metadata.json` in the event the user does not provide it to avoid those issues.

**Comment by vasukulkarni** [comment]
> This is to be expected then. Essentially what is happening is that the user is specifying a `cluster_path` that does not have a `metadata.json` file to pull the cluster name from. Since we can't determine what the cluster name is from the provided `cluster_path`, the user will need to specify the cluster name with `--cluster-name`. Normally, if the cluster is in a _good_ state the `metadata.json` file will exist so this shouldn't happen on every execution.
> 
> The reason this check is necessary is because we were executing certain tests (cluster expansion) without a cluster name and it was having adverse effects when creating things like cloudformation stacks. As such we attempt to pull the cluster name from `metadata.json` in the event the user does not provide it to avoid those issues.

As discussed in chat, this doesnt really look like an issue,  We had '--deploy' passed using existing cluster and its a user error. Thanks for pointing out.
