### ISSUE TITLE
Jenkins Workload, Build Failed on Proxy Cluster

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#2858]
Setup:
Proxy cluster
OCP Version:4.5
OCS Version:4.5

Run Test:
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/e2e/workloads/jenkins/test_jenkins.py

- On regular cluster,Jenkins workload work as expected 

- On Proxy cluster,Build Failed because git clone issue

- Error: There is an issue to clone pom.xml file from "https://github.com/red-hat-storage/ocs-workloads.git"
"error":{"message":"Error cloning remote repo 'origin'","type":"hudson.AbortException"},"parameterDescription":null,"startTimeMillis":1595516027696,"durationMillis":133296,"pauseDurationMillis":0,"stageFlowNodes":[{"_links":{"self":{"href":"https://jenkins-myjenkins-1.apps.lr4-dahorak-cl1.qe.rh-ocs.com/job/myjenkins-1/job/myjenkins-1-jax-rs-build/2/execution/node/9/wfapi/describe"},"log":null},"id":"9","name":"Git","execNode":"","status":"FAILED","error":{"message":"Error cloning remote repo 'origin'","type":"hudson.AbortException"},"parameterDescription":"https://github.com/red-hat-storage/ocs-workloads.git","startTimeMillis":1595516027774,"durationMillis":133181,"pauseDurationMillis":0,"parentNodes":["8"]}],"allChildNodeIds":["9"]}]}

- Need to adjust build config yaml file when use proxy cluster:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/workloads/jenkins/buildconfig.yaml

**Comment by dahorak** [comment]
@OdedViner, If I remember it correctly, when we were debugging this issue a month ago, this can be solved by configuring `http_proxy`, `https_proxy` and `no_proxy` env variables for the pod. Working solution seems to be to add following line with proper configuration to the `podTemplate` section (e.g. bellow `volumes: ...` on line 16):
```
  envVars: [podEnvVar(key: 'http_proxy', value: '<http_proxy>'), podEnvVar(key: 'https_proxy', value: '<https_proxy>'), podEnvVar(key: 'no_proxy', value: '<no_proxy>')]
```
See also https://www.jenkins.io/doc/pipeline/steps/kubernetes/

With this fix, it fails later on the command `mvn -f jenkins/maven01/pom.xml clean package -DskipTests=true`. The reason is the same - missing proxy configuration and the problem is, that `mvn` command doesn't consider the global/widely used env variables `http(s)_proxy` and proxy have to be configured somehow differently. I'm not maven guru, so I'm not sure what is the correct and best way, to configure proxy for maven in this job. If I remember it correctly, we've tried to use `MAVEN_OPTS` env variable with parameters like `-Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port> ...`, but it doesn't work, not sure why.
One possible working solution was to create `~/.m2/settings.xml` configuration file with content described in doc https://maven.apache.org/guides/mini/guide-proxies.html. But maybe there is some other - better - way...
