### ISSUE TITLE
Best implementation for collecting logs while deployment succeeds/fails

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#3056]
Currently, if a deployment is triggered while including `--collect-logs`, we execute `must-gather` for deployment and test-cases together, even if the deployment succeeds.

In order to prevent that, we delivered a new optional cli-argument named: `--collect-logs-on-success-run`, and then only if this argument is passed to **run-ci**, we grab logs on successful deployments as well.

That way, we avoid time-wasting for who does not want to grab logs after successful deployments.

We want to think a follow-up solution after this merges, in order to avoid duplication for similar cli-args, (`--collect-logs`,`--collect-logs-on-success-run`).
And so, it might be a great idea to change the behavior of log collections at all.

**Comment by jimdevops19** [comment]
@clacroix12 
I remember you suggested this [here](https://github.com/red-hat-storage/ocs-ci/pull/3025#discussion_r498364416) so I'm just leaving it here as your suggestion.

We could have one cli-argument only, named something like `collect-logs` or `--log-collection`.
And then this one parameter would accept optional values like `success | failure | both`

So in **ocs-ci** we can go with something similar to this:
```python
parser.add_argument("--collect-logs-level", choices=['success','failure','both'])
```
And on Jenkins, we can use **choiceParam** with those values.

**Comment by mbukatov** [comment]
From my perspective, it would make sense to have the following ways to control must gather:
- never
- on failure
- always

With *on failure* being the default. This is because such option will be default in jenkins (so we keep consistency here), and prevent external ocs-ci users to forget to collect additional evidence. Disabling must gather collection is useful mostly for test development, and asking people who develop a test to pass additional parameter to disable must gather collection seems ok to me.

**Comment by clacroix12** [comment]
I would also like to suggest we change the name from `--collect-logs` to `--must-gather` or something similar that more clearly informs users that this is specifically for "must gather". Collect logs is very vague and could mean a number of things given the scope of ocs-ci.
