### ISSUE TITLE
dont return yaml output by default for oc exec

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#312]
we may run many commands whose output will not be yaml safe loadable, lets take that as an option when we run the oc_cmd 

ex: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs/ocp.py#L74

**Comment by zmc** [comment]
I would encourage simply not doing anything magical here, and returning the output. The caller must know what format to expect, and asking them to simply perform a one-liner isn't a large burden.

It also clears up the incorrect return type in the docstring.

**Comment by RazTamir** [comment]
As we are wrapping oc cli commands let's act like it:
If the caller asked for output as yaml, yaml.load the output (default is true as this is more common use case). 
In case not, just return the output string. 

BTW, this issue came from the workload PR if I'm not mistaken, and it will need to be dict (yaml) as well for easier accessing to the output from fio

**Comment by vasukulkarni** [comment]
I am thinking the same to set default to True to not break the existing test cases, @zmc I agree with your statement, return the raw stdout and let the caller decide, but I dont want to break the existing tests so just going to default to True for now and fio test will set it False when it call run_cmd.

**Comment by vasukulkarni** [comment]
Fixed
