### ISSUE TITLE
TypeError: 'BackingStore' object is not subscriptable when calling check_backingstore_state function

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#3172]
```
        # Clean up the temp dir
        awscli_pod_session.exec_cmd_on_pod(
            command=f'sh -c \"rm -rf {LOCAL_TEMP_PATH}/*\"'
        )
    
        mcg_obj_session.check_backingstore_state(
>           'backing-store-' + backingstore1['name'],
            BS_OPTIMAL,
            timeout=360
        )
E       TypeError: 'BackingStore' object is not subscriptable
```
tests/ecosystem/upgrade/test_noobaa.py:124: TypeError

**Comment by fbalak** [comment]
There may be problem when `multiregion_mirror_setup_session` and `multiregion_mirror_setup` are executed in the same run.

**Comment by MeridianExplorer** [comment]
@fbalak - This is caused by a change in the design of backingstores returned by the `multiregion_mirror_setup` fixtures. 
The fix should be to replace `backingstore1['name']` with `backingstore1.name` (ditto for `backingstore2` in the same test)
I wanted to create a PR and test this, but my plate is somewhat full at the moment, so I thought about leaving my theory here

**Comment by fbalak** [comment]
Thank you, I will try it.
