### ISSUE TITLE
MCG tests and mcg_obj pull their S3 region out of the cluster's configuration

### ISSUE THREAD

**Issue by bernerhat** [red-hat-storage/ocs-ci#3338]
mcg_obj is pulling its region parameter from the environment configuration this parameter could be a non existing region in mcg.

we need to understand from the noobaa dev team the regions which are being used in the product and fix the object to retrieve the region which mcg is deployed on properly

**Comment by fbalak** [comment]
Should we get regions from configuration? I think that they should be part of clients in CloudManager objects. Currently we can get access keys and endpoints from cloud manager but we can not get the information about region. There is already implemented attribute `region` in `aws_client` but it is empty.
@MeridianExplorer what do you think?

**Comment by MeridianExplorer** [comment]
@fbalak - I think we should begin by splitting up the components that use regions;
First, we have MCG S3 commands. IIRC, they use signature version 4, which means a region has to be stated.
However, @bernerhat talked with @romayalon and Evgeniy from NB, and they reached the conclusion it doesn't really matter which region is stated.

Second, we have AWS commands. Those have to use the right region. But in those cases, it's also hardcoded.

I think the best practices moving forward will be:
- Hardcode an intentionally non-existent region to all MCG commands, i.e. `no-region`
- Create a constant list (under `constants.py`) containing all possible regions for each and every cloud provider. Once we have this, all tests that test a cloud provider and use a region will randomly pull one from the list.
- Make sure we use `us-east-2` when accessing `ocsci-test-files`

**Comment by fbalak** [comment]
Maybe we don't have to hardcode it. We already use auth.yaml with multiple cloud credentials. We can add the information about the region among credentials there.

**Comment by MeridianExplorer** [comment]
We could include the region information in auth.yaml, but I see three major problems with this flow:
1. I feel it wouldn't be the best practice to include data that isn't related to authentication, in a file named `auth.yaml`
2. If we won't include the entire list in there, then we'll have to pick just one. And that means we won't be able to randomize our tests between different regions. If we will, how would it be different to have a config file instead of including it under `constants.py`?
3. The tests will be dependent on `auth.yaml` being configured correctly. At the current moment, I'm already being contacted 2-3 times a week about problems that stem from an `auth.yaml` misconfiguration. I feel that adding this dependency can worsen the situation.
3.a. Perhaps, if we _will_ opt to go for a configuration file, we'll include it in our git repo. This way, point 3 won't be a problem.
