### ISSUE TITLE
test_multiple_pvc_creation_deletion_scale test cases are failing

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3371]
tests/e2e/scale/test_pvc_creation_deletion_scale.py::TestPVCCreationDeletionScale::test_multiple_pvc_creation_deletion_scale[ReadWriteOnce-CephBlockPool]
tests/e2e/scale/test_pvc_creation_deletion_scale.py::TestPVCCreationDeletionScale::test_multiple_pvc_creation_deletion_scale[ReadWriteMany-CephBlockPool]
tests/e2e/scale/test_pvc_creation_deletion_scale.py::TestPVCCreationDeletionScale::test_multiple_pvc_creation_deletion_scale[ReadWri! teMany-ce phfs]
tests/e2e/scale/test_pvc_creation_deletion_scale.py::TestPVCCreationDeletionScale::test_all_4_type_pvc_creation_deletion_scale

Console logs: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14757/
These test cases are failing on 4.6 rc2 build with error:

```
pv_dict = dict()
        format = "%H:%M:%S.%f"
        for pv_name in pv_name_list:
            # Extract the deletion start time for the PV
            start = [i for i in logs if re.search(f'delete "{pv_name}": started', i)]
            start = start[0].split(" ")[1]
            start_time = datetime.datetime.strptime(start, format)
            # Extract the deletion end time for the PV
            end = [i for i in logs if re.search(f'delete "{pv_name}": succeeded', i)]
>           end = end[0].split(" ")[1]
E           IndexError: list index out of range

ocs_ci/helpers/helpers.py:1426: IndexError ```

**Comment by ramkiperiy** [comment]
The problem here is need to provide some ample time for log generation to complete.
During deletion process, immediately after kube_job deletion we are collecting CSI logs to capture PVC delete data. With 10 or 100's of PVC logs are getting generated faster but when we perform delete of 500/1000/2000 PVCs in bulk, immediately collecting logs missing PVC delete data. Due to this reason in code list is getting empty data i.e. no respective PVC data in logs. 
Can fix this problem by providing timeout of 5mins. let me create a PR.

**Comment by ramkiperiy** [comment]
@keesturam @tiffanyn108 @wusui ^^

**Comment by ramkiperiy** [comment]
Observed similar problem in this test run https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15197/

**Comment by ramkiperiy** [comment]
Closing the issue, problem fixed with PR https://github.com/red-hat-storage/ocs-ci/pull/3431
