### ISSUE TITLE
Configure monitoring and registry during OCS deployment in external mode

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#3465]
Currently, monitoring and registry are not configured if OCS is deployed in external mode via ocs-ci. Hence other tests might fail which require monitoring/registry to be configured.

**Comment by petr-balogh** [comment]
@clacroix12 if you have some time, maybe you can take a look at this one? I think it will be just about move some part of code to the function and call it from external deployment or maybe make the current logic better to not return after that and finish with common stuff in the deployment function.  Thanks

**Comment by clacroix12** [comment]
@sidhant-agrawal @petr-balogh as far as I can tell the code which manages [monitoring](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L733-L770) and [registry](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L780-L781) is completely separate from where we [deploy with external mode](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L683-L685).

Perhaps I'm not understanding the issue correctly or this isn't the right part of the code I need to be looking at, if so please clarify. Do we at least have an example deployment that I can take a look at which these tests fail on external mode?

**Comment by sidhant-agrawal** [comment]
@clacroix12 yes, currently we are not calling those functions when deploying external mode but we can use same functions for external mode, provided we use correct storage class present in external mode.
Example failure in [test_must_gather](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/3491/testReport/tests.manage.z_cluster.test_must_gather/TestMustGather/test_must_gather_OTHERS_/) due to monitoring and registry related PVCs not present

**Comment by clacroix12** [comment]
@sidhant-agrawal Sorry, what I meant was I'm not seeing anything that is stopping this code from executing during a deployment with external mode. Am I looking at the right part of the code or is there something I am missing?

The only condition for monitoring is this:

```python
        if config.ENV_DATA.get("monitoring_enabled") and config.ENV_DATA.get(
            "persistent-monitoring"
        ):
```

The call to change the registry backend isn't in an `if` at all, so I'm wondering what is stopping this from happening for external mode deployments?

**Comment by petr-balogh** [comment]
@clacroix12 sorry for late reply here, the main issue here is that external mode is handled in separate function `deploy_with_external_mode` which is called here:
https://github.com/red-hat-storage/ocs-ci/blob/749a701f197557b3848b59aa6b1c3f51eb1ff779/ocs_ci/deployment/deployment.py#L721

The problem is that `return` here as     def deploy_ocs will finish after that line cause of we will return and you will never get to the rest of the code done in this function and the line you pointed out here:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L769

will never be reached in case of external mode.

The thing here is that we should not return from the external mode as we do not then call the rest of the code which is done later on like deployment of the monitoring and so on. So we should make it more robust and do not return from that function band if there are differences those should be then put to if block and not be called in case of external mode but common staff can be for sure handled in this common deploy_ocs function or called from here, or please come up with other better solution to not disconnect here between two different deployments with common staff which should be called and prevent the next implementations that some other common staff will be missed for one or the other deployment type.

Thanks

**Comment by clacroix12** [comment]
@petr-balogh ah! I completely missed that we were returning this instead of just simply calling it, thank you for the clarification.

@sidhant-agrawal I don't know all of the specifics around external mode so if there is anything in the common `deploy_ocs` function that we definitely don't want to run after we have called `deploy_with_external_mode` please let me know and I'll make sure we set conditions for executing them.

**Comment by sidhant-agrawal** [comment]
All `Ceph pods` and `CephFilesystem on OCP side` related checks are not applicable for external mode.
So we will have to skip those checks present between [deployment.py#L725](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L725) and [deployment.py#L766](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L766)
