### ISSUE TITLE
jenkins will not post test results if a new commit is pushed to the PR

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#3477]
I have seen this before and recently on this run from Tiffany https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15485/ , when the commit is pushed in the middle of the PR run, jenkins will not post the results back to the PR. we should look into what is causing this limitation.

**Comment by petr-balogh** [comment]
I don't think it's related to pushed commit in the middle of running job. I saw this already 3 times and root cause of this that in the PR validation job we see this:

`Error when copy artifacts or creating report: ERROR: java.io.IOException: Remote call on ocs-ci-jslave-3 failed`

We didn't find out yet the reason behind it and the traceback basically doesn't tell us anything.
I am adding more detail to print whole exception message to see more details here:
https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/455

Hope this will help us to identify the issue.
