### ISSUE TITLE
Increase the default thread count for smallfile workload

### ISSUE THREAD

**Issue by keesturam** [red-hat-storage/ocs-ci#3500]
Currently, smallfile workload tests run with 4 threads. A reasonable value for thread needs to be updated for smallfile workload. 

background: https://docs.google.com/document/d/1thRo0AGK2af2ECUGiLOBQ28UQtzWLX-2iYxeSfdRy9s/edit?disco=AAAAHLNU3TY

@bengland2 Any thoughts on what could be a reasonable value?

**Comment by bengland2** [comment]
@keesturam depending on the configuration, 4 threads may not be enough to drive the system hard.   For example, if you have 50 OSDs, then 4 threads can only keep a small fraction of these OSDs busy (roughly 4/50).   But if you have writes going on, then with 3-way replication you would expect more like 12/50 of the OSDs to be busy at any point in time.   My suggestion would be to make the thread count be = 2x OSD count.  

in the past, there have been problems with having lots of smallfile threads because some threads would finish earlier than others.   An initial attempt to fix this was done with the --pause parameter but there are 2 problems here: a) you don't know the right value of --pause (microseconds) to use until you've run the test in that configuration, and b) the value that makes sense for one operation type (e.g. create) doesn't make sense for another (e.g. delete).     I merged a possible solution to that called --auto-pause in smallfile recently.    This automatically adjusts the pause time based on the response time of the system. I've  been testing it out with OCS in the last couple weeks but have not merged the fixes into the benchmark-operator and benchmark-wrapper yet, hope to get that done this week.    Look for PRs there.    [Here's the autopause code](https://github.com/distributed-system-analysis/smallfile/pull/27)

**Comment by Avilir** [comment]
this issue was fix with #4986
