### ISSUE TITLE
use ci-pause in one of the tier4 stage test to mimic complete reset

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#3535]
we have `ci-pause --cluster-path /home-dir/cluster-path --action [stop|start]` to reset the cluster all at the same time, since this seems to be supported(based on discussion in ocs4 group) we can introduce this as a stage job in one of the tier tests and continue after the stage.

**Comment by petr-balogh** [comment]
@vasukulkarni can you point at the documentation and add some more details about scenario as I think we need to follow some exact steps how the restart should be done.  The ci-pause will shutdown all the machines or how does it work?

I remember there were few OCP issues on the restart cluster before 24 hours after deployment which could lead to broken OCP cluster.  @dahorak can you please check on that issue if it was finally fixed or the issue is still there?

**Comment by dahorak** [comment]
> I remember there were few OCP issues on the restart cluster before 24 hours after deployment which could lead to broken OCP cluster. @dahorak can you please check on that issue if it was finally fixed or the issue is still there?

I didn't tried it recently and I only find [this article](https://access.redhat.com/solutions/4271712) and [this blog post](https://www.openshift.com/blog/enabling-openshift-4-clusters-to-stop-and-resume-cluster-vms) - both are already more than one year old and there is no note in the recent documentation, so maybe it is already fixed.
