### ISSUE TITLE
pytest-ordering is not maintained anymore and contains a warning bug

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#3600]
One of plugins we use, [pytest-ordering](https://github.com/ftobia/pytest-ordering), has ceased development about a year and a half ago.
A community member then created [pytest-order](https://github.com/mrbean-bremen/pytest-order), fixing many of the issues reported in `pytest-ordering`, including extra features, and also a fix for the warning we see in some of our runs - 
```
venv/lib/python3.6/site-packages/_pytest/mark/structures.py:327
  /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.last - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,
```

The warning is not critical, and does not affect code execution at all. It's mostly cosmetic.

`pytest-order` is *not* directly comaptible with `pytest-ordering`, because the marker name was changed from `run` to `order` - so this might not be an obvious change.

**Comment by vasukulkarni** [comment]
@MeridianExplorer what exactly is failing, we have a unit test that does test the order, can you paste the logs that failed the ordering?

**Comment by MeridianExplorer** [comment]
@vasukulkarni - Gladly, nothing is failing :) It just shows a warning in our logs, as shown in the issue's description.
`PytestUnknownMarkWarning: Unknown pytest.mark.last - is this a typo?...`
For example, it can be seen in the log after every single deployment - i.e. [here](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/221/console)
![image](https://user-images.githubusercontent.com/19227853/106921408-a7f83300-6714-11eb-901a-7d43b40029cc.png)

**Comment by vasukulkarni** [comment]
Oh thanks!, Now If I read it again, it makes sense :grinning:

**Comment by petr-balogh** [comment]
@MeridianExplorer I think we don't see this warning anymore in the console output. Or can you point the execution you saw it lately? 

I think that it got fixed by this line:
https://github.com/red-hat-storage/ocs-ci/blob/master/pytest.ini#L41

And for now I would not consider to change the plugin as part of this issue.

If you would like to have plugin changed - this needs to be tested a lot for upgrade scenarios as this is the place where we use it a lot.

I am closing this one based on comment above - if you feel otherwise, feel free to re-open or open new issue for plugin change.

Thanks
