### ISSUE TITLE
test_node_restart.py fails with "mcg-obc" already exists error at sanity_helpers.create_resources check

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#3621]
ocs-ci results for OCS4-6-Downstream-OCP4-6-VSPHERE-UPI-FIPS-1AZ-RHCOS-VSAN-3M-6W-tier4a (BUILD ID: v4.6.1-206.ci RUN ID: 1609114011)

The actual tests passed in the test suite but below error was seen during sanity_helpers.create_resources check which is run for sanity check at the end of the test case.

ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc create -f /tmp/obc_mcg_dataq92he_20. Error is Error from server (AlreadyExists): error when creating "/tmp/obc_mcg_dataq92he_20": objectbucketclaims.objectbucket.io "mcg-obc" already exists

The failure is at https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/helpers/sanity_helpers.py#L71, in test_nodes_restart test the obc was created and not deleted. Since the obc is still present, the next tests calling sanity_helpers.create_resources() failed at obc creation as the obc with same name already exists on the cluster.

Output for one of the failed test:
NAMESPACE                                  NAME                 BUCKET-NAME   STORAGE-CLASS                          BUCKET-CLASS                  PHASE   
namespace-test-f38cf77cd52d4f228b619683f   ceph-delete-bucket                 ocs-external-storagecluster-ceph-rgw                                         
openshift-storage                          mcg-obc              noobaa-obc    openshift-storage.noobaa.io            noobaa-default-bucket-class   Bound

**Comment by ebenahar** [comment]
Examined the code in sanity_helpers. The following change is needed for making OBC creation and deletion more robust in this file:

OBC creation does not use bucket factory fixture, but rather creates the OBC with a CLI command:
https://github.com/red-hat-storage/ocs-ci/blob/dc6f2675b3218813532a759013feb71ee175df47/ocs_ci/helpers/sanity_helpers.py#L95
This is problematic because, in the case of a test failure, the bucket will not get deleted as the teardown does not include OBC deletion in such a case.
In order to fix this, we need to add a bucket factory and RGW bucket factory to:
 https://github.com/red-hat-storage/ocs-ci/blob/dc6f2675b3218813532a759013feb71ee175df47/ocs_ci/helpers/sanity_helpers.py#L48)
