### ISSUE TITLE
Custom cephblockpool creation fails on cluster with arbiter

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#3962]
Custom cephblockpool creation fails on cluster with arbiter, with the following error:

```
2021-03-10T04:26:16.357378897Z 2021-03-10 04:26:16.357367 E | ceph-block-pool-controller: failed to reconcile. invalid pool CR "cbp-test-fb9a4d549e1848f590d81ad356c3e80" spec: pools in a stretch cluster must have replication size 4
```

Test run reference:
- https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/1154/
- `ocsci-jenkins/openshift-clusters/pbalogh-dr-new/pbalogh-dr-new_20210309T140619`
- RUN ID 1615329870

**Comment by nehaberry** [comment]
@Martin Bukatovic @Pratik Surve could you check if it can get an assignee and whether a fix can be sent for this issue. This  will unblock a lot of test cases for arbiter mode.

**Comment by mbukatov** [comment]
With arbiter stretch cluster, one needs to use replica 4. Alternative replication factors such as 2 or 3 are not valid.

This means that:
- test cases which explicitly use different replication factors should be skipped on arbiter cluster
- test cases which are expected to use the default replication factor, but have it hard coded as "3" should be upgraded so that it uses 4 when executed on a stretch cluster

This task should be assigned to authors of the test cases.

**Comment by shyRozen** [comment]
Missed that one. I think of the following options:
1. Skip this cli testcases and write new one in UI for Pool as it is by default suppose to be 4 for arbiter.
2. Skip this cli testcases and write new one for arbiter via CLI.
2. Change all the testcase for arbiter which I think it's a lot of overhead. 
What do you think? @PrasadDesala @mbukatov 
By the way do we have something in ocs-ci to skip some of parameterize?
