### ISSUE TITLE
OCS-CI's HAProxy is misconfigured (SSL_ERROR_RX_RECORD_TOO_LONG / ERR_SSL_PROTOCOL_ERROR)

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#4209]
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/2212/

**Comment by MeridianExplorer** [comment]
In this particular case, it seems that the cluster was affected by a TLS misconfiguration. This has led to an inability to connect to the cluster over HTTPS. Both Selenium and the RPC request failed because of the SSL error, and the web console is also inaccessible.

**Comment by OdedViner** [comment]
same issue for 
```
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_PROTOCOL_ERROR
E         (Session info: headless chrome=90.0.4430.93)

venv/lib64/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/688/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity/TestAddCapacity/test_add_capacity/


![image](https://user-images.githubusercontent.com/61982127/117298895-8e37ca80-ae80-11eb-983e-7462f48ee628.png)

**Comment by MeridianExplorer** [comment]
I noticed that we do get a concrete error in the logs - 
`SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")`
According to a quick search, it stems from using HTTPS for endpoints / ports that only serve HTTP. 
This also seems to be in line with Firefox's `SSL_ERROR_RX_RECORD_TOO_LONG `

**Comment by MeridianExplorer** [comment]
The problem is caused by https://github.com/red-hat-storage/ocs-ci/blob/7daf524f6dbeb038115860bc6b96167fe6cd2c7c/ocs_ci/utility/load_balancer.py#L102-L115
Which adds all new node IPs with port `80` to the `router-https` section of the LB config.

**Comment by vavuthu** [comment]
@MeridianExplorer could you let me which Test case its failed with error "SSL_ERROR_RX_RECORD_TOO_LONG / ERR_SSL_PROTOCOL_ERROR" and also can you point me to test logs

**Comment by MeridianExplorer** [comment]
These errors are not shown in the logs - they're specific to Chrome and Firefox when attempting to connect to the cluster's web console.
In the run logs, the error appears in two ways:
1. `OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]` (Prometheus)
2. `Max retries exceeded with url: /rpc (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))` (MCG RPC token retrieval)
You can check the logs of run 1637846152, `test_rgw_host_node_failure`, for example.

For the record, I have already fully analyzed the issue, and editing the HAProxy's `router-https` section to point to `443` instead of `80` fixed a live cluster with the problem. (See the email thread of run 1637962015)

**Comment by MeridianExplorer** [comment]
#5320 is only a workaround PR - a proper solution still needs to be implemented

**Comment by dahorak** [comment]
@MeridianExplorer, do we have some more recent occurrences or reproducer? Or do you have some more info, why the https://github.com/red-hat-storage/ocs-ci/pull/5320 is not a fix and only workaroud?

**Comment by petr-balogh** [comment]
Assigned to @dahorak .

**Comment by dahorak** [comment]
I tried to simulate it and explore the issue here and from what I understood the fix in PR https://github.com/red-hat-storage/ocs-ci/pull/5320 seems to be legitimate and I don't see any big problem with it (I'm not sure if there is any better way how to update remote file with haproxy configuration than calling the `sed` command and it looks quite ok to me).

So the question is, if this issue is still valid after the merge of PR https://github.com/red-hat-storage/ocs-ci/pull/5320 and if yes, what are the exact steps to reproduce the issue (or more recent CI executions where it was observed) and does it happen every time or is it occasional issue?
