### ISSUE TITLE
OCS upgrade test sometimes fails with CSV not reaching Succeeded 

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#4246]
For example, in this run [1], `test_upgrade` failed with:
```
ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed out after 725s running check_if_upgrade_completed("channel"="stable-4.7", "csv_name_pre_upgrade"="ocs-operator.v4.7.0-364.ci")
```
While in the must gather [2], we can see that the CSV is in Succeeded:
```
NAME                         DISPLAY                       VERSION        REPLACES              PHASE
ocs-operator.v4.7.0-364.ci   OpenShift Container Storage   4.7.0-364.ci   ocs-operator.v4.6.4   Succeeded
```

[1] http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/ebenahar1-up/ebenahar1-up_20210430T131146/logs/
[2] http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/ebenahar1-up/ebenahar1-up_20210430T131146/logs/failed_testcase_ocs_logs_1619800358/test_upgrade_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-0e929cb3857e60e2f154be3ce2f4a2aa2924b2e660e5cf96b9a5f64897a0d072/namespaces/openshift-storage/oc_output/csv

**Comment by petr-balogh** [comment]
Finally was able to find out the root cause of the issue @ebenahar .

You've scheduled the whole execution with the upgrade, but you also ran the tests: RUN_TEST option here:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/2454/parameters/

Where you explicitly set TEST_MARK_EXPRESSION to run the upgrade again as you put value: ocs_upgrade .

This case I see it ran run-ci commands 3 times. Deployment, upgrade, and again the upgrade.

Please this case if you would like to run only upgrade you need to disable RUN_TEST and if you would like to cove only upgrade without any pre_upgrade and post upgrade tests you need to update UPGRADE_TEST_MARK_EXPRESSION .
