### ISSUE TITLE
Add capacity test via UI is not  stable.

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#4318]
"Add capacity" test via ui is not  stable because of a login issue.
I don't understand what is the difference between these ci builds, some builds failed and some builds pass

I added this pr to resolve SSL error.[merged]
https://github.com/red-hat-storage/ocs-ci/pull/4270

What do you think? How can the issue be resolved?

pass:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/826/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity/

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/813/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity/

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/771/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity/

failed:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/809/testReport/tests.manage.z_cluster.cluster_expansion.test_add_capacity/TestAddCapacity/test_add_capacity/
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

venv/lib64/python3.8/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException

**Comment by petr-balogh** [comment]
Hey @OdedViner , the login happen only once at the start or many times?  Can some re-try help here if it's some temp connection issue - as because of PSI issues I can imagine there could be some issue to contact the outside network - so maybe timeout issue but not sure what happened. Here, I think we can try to add re-try - like 3 attempts with that Exception TimeoutException and re-try to see if it is just temp issue and second, third re-try will be OK or not.

But now I am confused as in the failed test you linked:

It failed cause of:
```
>       mirror_registry = config.DEPLOYMENT["mirror_registry"]
E       KeyError: 'mirror_registry'

ocs_ci/utility/utils.py:2700: KeyError
```

Which was different issue:
https://github.com/red-hat-storage/ocs-ci/issues/4305
 was fixed by @vavuthu two days back here:
https://github.com/red-hat-storage/ocs-ci/pull/4281
