### ISSUE TITLE
GCP, Several "ceph files" are missing on must-gather directory on OCS4.8

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#4490]
these files do not exist on must-gather directory:
['ceph_osd_pool_ls_detail', 'ceph_report', 'ceph_status', 'ceph_time-sync-status', 'ceph_versions']

['ceph_osd_blocked-by_--format_json-pretty', 'ceph_osd_df_--format_json-pretty', 'ceph_osd_lspools_--format_json-pretty', 'ceph_osd_numa-status_--format_json-pretty', 'ceph_pg_dump_--format_json-pretty', 'ceph_report_--format_json-pretty', 'ceph_service_dump_--format_json-pretty']

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1236/testReport/tests.manage.z_cluster.test_must_gather/TestMustGather/test_must_gather_JSON_/

**Comment by mbukatov** [comment]
@OdedViner This looks like a product bug. If you really believe that this is a ocs-ci issue, maybe you could explain your reasoning in more detail, so that we can agree with such conclusion, and also understand what would one need to fix in ocs-ci.

Right now, I see that on given platform, some must gather files were missing, and the test of must gather feature complains about that. There is nothing obviously wrong with the test at first sight.

**Comment by OdedViner** [comment]
No OCS-CI issue [product-bug]
