### ISSUE TITLE
couple more fixes for deployment_openshift_logging.py

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#488]
Fix couple more comments from Karthik and Coady for PR https://github.com/red-hat-storage/ocs-ci/pull/414

**Comment by vasukulkarni** [comment]
@Shrivaibavi Along with those fixes, please add the test script in E2E folder.

**Comment by Shrivaibavi** [comment]
@vasukulkarni @keesturam @clacroix12  The automation test sprint is going on. The testcases will be soon sent as a new PR.
I would be happy to receive a suggestion from you. Can we have testcases for openshift-logging aligned up like this in a same file.
```
cat logging_testcases.py

Class test_logging():
    def setup():
        Install openshift-logging
    def testcase1():
    def testcase2():
    .
    .
    .
    .
    .
    def teardown():
        teardown_openshift_logging
```
Keep on adding testcases as a function under the same file ?

**Comment by Shrivaibavi** [comment]
Please suggest.

**Comment by clacroix12** [comment]
@Shrivaibavi Since they are all openshift-logging test cases then yes, we can have a `class TestOpenshiftLogging` with several test case methods in that class. Keeping tests organized in this way is actually preferred. Ensure that the name of the test cases reflect what they are testing. 

Regarding the `setup` and `teardown` methods here in the class, let's create a class scope fixture that will install and setup openshift logging, as well as (in it's finalizer) handle tearing it down. This way we can decorate the class or test methods with this fixture to provide the necessary resource to test with.

**Comment by Shrivaibavi** [comment]
@clacroix12 Noted. Thanks for your suggestion.

**Comment by vasukulkarni** [comment]
@Shrivaibavi what coady said, I will recommend that you add test by test in different PR's rather than trying to add bunch of them together,  It keeps the PR short and easy to review.
