### ISSUE TITLE
Link to must-gather and other logs are missing for test failure analysis on Report portal

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#5156]

**Comment by clacroix12** [comment]
Hey @am-agrawa, can you elaborate a bit more on this? Where in ReportPortal do we need to link to the must-gather logs. The test case logs are attached to any test cases that fail but we can also provide a link if that is necessary as well. This is not the case for must-gather tho. For those you will need to go to the jenkins job (link is in the launch description). We can add a link directly to the logs here as well to make things easier but in the meantime you can use the job link.

**Comment by am-agrawa** [comment]
Hi @clacroix12, We just need the link for each run which should eventually take us to the must-gather logs. As of now, I do not see any link which helps to find out which Jenkins job does the run belongs to. As there is no Run Id on the report portal like the one we have in emails for each Jenkins run, so it is getting very difficult to find the test runs and analyze them. Hope I was able to explain the scenario.

**Comment by clacroix12** [comment]
I think the issue here is that the link from jenkins or the email report takes you directly to the launch instead of the launch list, so the description is a bit more hidden.

In this screenshot there is an icon i have circled in red, if you hover over this icon you will be able to view the launch description.

![Screen Shot 2021-11-30 at 9 31 12 AM](https://user-images.githubusercontent.com/1605721/144098346-e94ca67a-12d9-4f65-9c90-569e109d5fcc.png)

![Screen Shot 2021-11-30 at 9 31 20 AM](https://user-images.githubusercontent.com/1605721/144098374-71d6128e-eb94-48cc-a57b-3c4866a21ac8.png)

You should then be able to mouse down to the description and click on the link to the jenkins job. 

Unfortunately this is simply how the ReportPortal UI works at the moment, I would really like to see the information on the launch be more readily visible in this view. I can always open an issue on the ReportPortal repo to see if this is something they would consider.

As a workaround to this we could always duplicate the launch attributes / description to the testsuite level so they would be visible there as well. This would be easier to see and click on than having to hover over the description / attributes icons at the top.

**Comment by am-agrawa** [comment]
Thanks @clacroix12. This was really helpful and I completely agree with your points. Report portal UI has a lot of scope for improvement.
