### ISSUE TITLE
mcg-cli not found in /data

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#5314]
As it was a failure that happened in prod job - VSPHERE UPI 1AZ RHCOS VSAN 3M 3W upgrade-ocs-auto, raising this issue here.

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/2833/consoleFull

Complaining about mcg-cli binary not found in the data.

**Comment by MeridianExplorer** [comment]
This was most likely caused by a failure to copy the binary from the pod.
This is not an automation issue per se, and is tracked [here](https://bugzilla.redhat.com/show_bug.cgi?id=2011845).
New CLI retrieval flows should be implemented as part of solving #2850 and #2477, so I believe this issue can be closed.

**Comment by petr-balogh** [comment]
@MeridianExplorer I think this is upgrade from 4.5 to 4.6. And we need to have this fix merged:
https://github.com/red-hat-storage/ocs-ci/pull/5235

Is the PR up ready for testing, merge?

**Comment by MeridianExplorer** [comment]
@petr-balogh - Positive

**Comment by petr-balogh** [comment]
Can be closed as this one #5235 was merged.
