### ISSUE TITLE
Blocker: HTML test report generated by ocs-ci is reaching gigantic file sizes

### ISSUE THREAD

**Issue by haubenr** [red-hat-storage/ocs-ci#5567]
Today I noticed that the the HTML reports generated by ocs-ci for e.g. test tier runs are all of a sudden massive in size, e.g.:

IBM Z / LinuxONE:
tier4a: > 450MB

IBM Power Systems:
tier4a: > 580MB
tier1: > 660MB
tier2: > 980MB

These large HTML reports can no longer be handled properly as both Firefox and Chrome are unable to load / render them.

This issue was introduced into ocs-ci only recently, it's present in branches `master` as well as `stable`.

**Comment by clacroix12** [comment]
I'm not sure when this change was introduced but I think this is due to the entire log being captured in the html report for passed test cases. If you view http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-154vuf1cs36-t4a/j-154vuf1cs36-t4a_20220308T163009/logs/deployment_report_1646756339.html you can see the log being displayed below the test case status.

**Comment by petr-balogh** [comment]
I think it might be related to the issue I brought up in email here:
https://lists.corp.redhat.com/archives/ocs-qe/2022-March/000258.html

We need to identify the root cause of this ASAP.

**Comment by petr-balogh** [comment]
I think it might be related to the issue I brought up in email here:
https://lists.corp.redhat.com/archives/ocs-qe/2022-March/000258.html

We need to identify the root cause of this ASAP.

**Comment by petr-balogh** [comment]
Might be related to this issue:
https://github.com/pytest-dev/pytest-html/issues/171

And with recent update of pytest and change of one parameter here:
https://github.com/red-hat-storage/ocs-ci/commit/5fd10d5e3bba0f650bed445f9710917d2dfb2caa

I hope that upgrade of pytest-html will fix the issue for us.
