### ISSUE TITLE
Must-gather helper pod is detected as a leftover and causes teardown failures

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#5618]
[Example](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3430/testReport/junit/tests.manage.mcg.test_bucket_creation/TestBucketCreation/test_bucket_creation_1_CLI_PVPOOL_/)

**Comment by jilju** [comment]
This issue was reproduced in the run 1659888339(RUN ID)

**Comment by keemano** [comment]
This issue was reproduced in the run: 1675262490
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6775/
Logs URL: [http://magna002.ceph.redhat.com/ocsci-](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-236ai3c33-ua/j-236ai3c33-ua_20230201T080619/logs/)

**Comment by mashetty330** [comment]
This issue still exists
