### ISSUE TITLE
Tier2 test "test_crashcollector_pod_existence_on_ceph_pods_running_nodes" fails on baremetal with "IndexError"

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#5671]
**Test File** : tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py

https://github.com/red-hat-storage/ocs-ci/blob/cea62d663aa434ceec1e645e214cd253cb1aa2ba/tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py#L85

```
self = <tests.manage.z_cluster.cluster_expansion.test_crashcollector_pod_existence_on_ceph_pods_running_nodes.TestAddNodeCrashCollector object at 0x3ff7760b400>
add_nodes = <function add_nodes.<locals>.factory at 0x3ff67ffc820>
node_drain_teardown = None

    def test_crashcollector_pod_existence_on_ceph_pods_running_nodes(
        self, add_nodes, node_drain_teardown
    ):
        """
        Add node with OCS label and verify crashcollector created on new node
    
        """
        failure_domain = get_failure_domin()
        logger.info(f"The failure domain is {failure_domain}")
    
        if failure_domain in ("zone", "rack"):
            old_node_rack_zone_dict = get_node_rack_or_zone_dict(failure_domain)
            logger.info(f"The old node rack/zone dict is {old_node_rack_zone_dict}")
    
        old_nodes = get_node_names()
    
        logger.info("Add one worker node with OCS label")
        add_nodes(ocs_nodes=True, node_count=1)
    
>       new_node_name = list(set(get_node_names()) - set(old_nodes))[0]
E       IndexError: list index out of range
tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py:85: IndexError

IndexError: list index out of range
```

Environment : Baremetal, s390x

[test_crashcollector_pod_existence_on_ceph_pods_running_nodes.zip](https://github.com/red-hat-storage/ocs-ci/files/8409144/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.zip)

**Comment by Sravikaz** [comment]
This issue is not resolved and is also observed on the latest odf build ` 4.11.0-137` and a skip marker `skipif_bm` needs to be added for this testcase

**Comment by PrasadDesala** [comment]
This test has to be skipped on Baremetal as the steps involve adding a new worker node.

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6998/291593/291775/291776/log
Run ID: 1669980540
Test Case: test_crashcollector_pod_existence_on_ceph_pods_running_nodes
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier2
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6270/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003bu1cni30-t2/j-003bu1cni30-t2_20221202T102339/logs/Error Message: ```IndexError: list index out of ran```
