### ISSUE TITLE
test_mcg_data_deduplication sometimes does not compress to expected value

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#5708]
Message: AssertionError: Data reduction is insufficient. 2454 bytes reduced out of 90363194

**Comment by parikshithb** [comment]
Seeing this intermittent issue again in https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/all/5187

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7015/292448/292545/292555/log
Run ID: 1670007275
Test Case: test_mcg_data_deduplication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: AZURE IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6280/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-004zi3c33-uba/j-004zi3c33-uba_20221202T083924/logs/
Error Message: ```AssertionError```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6976/290813/290929/290938/log
Run ID: 1669952976
Test Case: test_mcg_data_deduplication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI ENCRYPTION 1AZ RHCOS VSAN LSO VMDK 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6273/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003vue1cslv33-uba/j-003vue1cslv33-uba_20221201T230828/logs/
Error Message: ```AssertionError```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6959/290051/290168/290177/log
Run ID: 1669936593
Test Case: test_mcg_data_deduplication
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: RHV IPI 1AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6267/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-011ri1c33-t1/j-011ri1c33-t1_20221201T222122/logs/
Error Message: ```AssertionError```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6949/289361/289478/289488/log
Run ID: 1669941053
Test Case: test_mcg_data_deduplication
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI KMS VAULT V1 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6276/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-078vukv11cs33-t1/j-078vukv11cs33-t1_20221201T233022/logs/
Error Message: ```AssertionError```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6942/289052/289163/289169/log
Run ID: 1669937787
Test Case: test_mcg_data_deduplication
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6269/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-016bu1cni30-t1/j-016bu1cni30-t1_20221201T223415/logs/
Error Message: ```AssertionError```

**Comment by sagihirshfeld** [comment]
Known BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2119031
