### ISSUE TITLE
Markers skipif_ms_provider and skipif_ms_consumer are not working correctly

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#5776]
The markers `skipif_ms_provider` and `skipif_ms_consumer` are not working correctly. For example in [this run](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/86/consoleFull) first (default) cluster is consumer and second cluster is provider but all the tests were skipped even though the tests have `@skipif_ms_provider` mark.

Initially I was thinking, that the problem is in `gather_version_info_for_report(...)` function called in `ocs_ci/framework/pytest_customization/ocscilib.py:pytest_configure` - there is raised exception, but it is properly handled.

The main problem here probably is, that the `@skipif*` marks are processed during collecting the tests, before the default context is fully set (not sure about the exact order). So now, it seems, that it depend on the last specified cluster, no matter which cluster is specified as _default_ (the first one or specified via `--default-cluster-context-index`)

**Comment by petr-balogh** [comment]
The mark.skipif decorater is evaluated at the time when pytest collect the tests which might be problematic when you expect the tests to switch the context in the middle of the run. For programatic approach we can use pytest.skip directly in test case instead of the marker skipif.

https://docs.pytest.org/en/7.1.x/how-to/skipping.html
