### ISSUE TITLE
Test skipif checks being performed on tests that aren't specified to run

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#5788]
I noticed that we have `skipif_some_condition` checks being performed on dozens of tests at the start of any execution, regardless of the fact that they aren't even marked with the test marker specified when executing `run-ci`. This is wasting a lot of time at the beginning of executions, especially when bugs appear in these checks. 

We should only be performing these checks on tests that have been officially gathered by pytest for the current execution, not prior to that.

You can see what I'm talking about in this execution where only `deployment` tests should be executed: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/12044/consoleFull

**Comment by petr-balogh** [comment]
Hey @clacroix12 , I already partially covered it in the other issue here:
https://github.com/red-hat-storage/ocs-ci/issues/5789#issuecomment-1110677320

The reason behind why those checks are running before is because of we actually deleting them from pytest collection with the pytest hook `pytest_collection_modifyitems`.

Those tests are then deleted from collection (not just skipped) to not have those tests even reported as skipped but they will not present at all.

E.g. skipif_upgraded_from is really performed only on those tests items which are decorated by this marker.
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L217

If you know the better way how to let pytest first to only collect needed tests and perform such logic on top of the selection of tests it will be better as then those checks will not be performed on all items but already on those selected by pytest.  But I am not aware of how to achieve this by pytest as I know only this hook `pytest_collection_modifyitems`.

**Comment by clacroix12** [comment]
@petr-balogh is there a particular reason why we can't have these tests marked as skipped with a legitimate reason such as OCS version? If not having them in the report is imperative then I can try to do some research into it. I'm not sure how much information we have on the test items but off the top of my head I'm thinking that we could check the test item markers against the list of markers specified for the pytest execution and only perform checks on those items as the rest won't be collected anyways.
