### ISSUE TITLE
get_ocs_csv loops for 7 hours waiting for nonexistent OCS version

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#5789]
I have encountered this issue while testing ACM Hub Downstream deployments where there is no OCS being deployed. We have a check on some of our tests to determine whether they will be skipped or not, one of which is [skipif_upgraded_from](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L3396-L3423). This check is calling `get_ocs_csv` which is failing due to the fact that OCS is not installed on this cluster, which then proceeds to loop for seven hours before the execution finally fails.

Not only should this check be taking into consideration the possibility that OCS doesn't exist in the test environment, but we should be moving on much sooner. In addition, these checks shouldn't even be performed unless they are on tests that are being specified to actually run. For this example I'm trying to run a `deployment` test, yet we have dozens of checks being performed to determine whether or not some tests can be skipped, even though they won't be executed anyways. This is a big area where we can make performance improvements as these checks take a non-trivial amount of time to execute. I have opened an [issue](https://github.com/red-hat-storage/ocs-ci/issues/5788) to track this as well.

You can see this behavior present in this execution: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/12044/consoleFull

**Comment by petr-balogh** [comment]
@clacroix12 what is happening is that we have this pytest hook:
`pytest_collection_modifyitems`
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L188
We do not perform those check in severla cases as you can see for deployment, if OCS deployment is skipped and so on.

Where we actually are trying to delete some of the tests from collection so they will not be in the report at all, so we will not see them as skipped for example but they will not be even collected by pytest.

And we have several checks which we perform to decide when such test should be deleted. One of the check you mentioned is skipif_upgraded_from which actually in the hook delete those items from collection - not just skip. 

In your job, you introduced scenario which is currently not valid for OCS-CI as the test execution requires the OCS to be present, so you cannot at the moment run the test execution against the cluster which has only OCP and ACM installed.

In the case of ACM deployment I think this is happening as a part of OCP deployment where OCS deployment is skipped, here we are fine as we are running deployment and those check are not performed. In the current logic of the multicluster job, the next step is to run import or install via ACM and following by installation of OCS on such clusters.  @jimdevops19 and @shylesh has more details about it.

Anyway, 7 hours is long time, and not sure why this doesn't fail much sooner and this I suppose should be fixed as part of this issue. Or what else do you think should be fixed here? As this is at the first place not valid configuration to run test execution against.

The issue that those check are performed is OK because we need to decide which tests should be completely removed from the collection and which not.

**Comment by shyRozen** [comment]
Hi @clacroix12 and @petr-balogh . My SNO deployment also doesn't have OCS operator. The second run-ci (the one after --deploy and before --teardown) tried to get ocs-operator for **7 hours** till it quit.
So first if ocs not installed we should skip this validation and second it shouldn't take 7 hours to realize that ocs is not installed
[qe-deploy-ocs-cluster/13726](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/13726/)

**Comment by petr-balogh** [comment]
@clacroix12 have you identify the place where the problem resides to decrease the timeout to some reasonable time?

**Comment by shyRozen** [comment]
For the progress this is the run-ci that triggers the endless check:
`run-ci --color=yes tests/ -m deployment -k '' --ocs-version 4.11 --ocp-version 4.11 --ocsci-conf=/tmp/DCRKJQVFDIYB '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/ocsci/production-aws-ipi.yaml --ocsci-conf=conf/deployment/vsphere/upi_1az_rhcos_vsan_1mw.yaml --ocsci-conf=ocs_ci/templates/lvmo-deployment/lvmo_deployment_5_disk_X_150GB.yaml --cluster-name jnk-pr5715-b2963 --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/test_results_1655682703.xml -o junit_suite_name=testsuite '--html=~/current-cluster-dir/logs/test_report_1655682703.html' --self-contained-html --bugzilla --email=srozen@redhat.com --squad-analysis`
This is running after deployment.
It now a time that I need to merge many PR regarding deployment and every one takes lock time + setup time + deplyment time + 7H + teardown time. It slow the progress. Please @petr-balogh @clacroix12 give this a priority to check if something can be done to avoid this.

**Comment by shyRozen** [comment]
By the way the link I've sent in my comment 8 days ago was leading to another job. Now it is the correct one. [qe-deploy-ocs-cluster/13725](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/13725/)

**Comment by shyRozen** [comment]
solved with [https://github.com/red-hat-storage/ocs-ci/pull/6082](https://github.com/red-hat-storage/ocs-ci/pull/6082)
