### ISSUE TITLE
tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#5817]
tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py::TestDynamicPvc::test_rwx_dynamic_pvc[CephFileSystem-Delete]
RWX Dynamic PVC creation tests with Reclaim policy set to Retain/Delete

OCP version 4.10.9
OC_OCS_VERSION: '4.9'

Steps to reproduce:
Run prep steps from [ocs-ci.readthedocs.io/en/latest/usage.html](https://ocs-ci.readthedocs.io/en/latest/usage.html)

sed -i 's/ocs_csv_channel:./ocs_csv_channel: "stable-4.9"/' ocs_ci/framework/conf/default_config.yaml
sed -i 's/default_ocs_must_gather_latest_tag:./default_ocs_must_gather_latest_tag: "latest-4.9"/' ocs_ci/framework/conf/default_config.yaml
sed -i 's/ocs_version:.*/ocs_version: "4.9"/' ocs_ci/framework/conf/default_config.yaml

run-ci tests/ --html report.html -m acceptance --cluster-path /home/kni/ocs-ci/cluster/ --cluster-name spk-factory-0 --ocs-version 4.9 --ocp-version 4.10 --collect-logs --collect-logs-on-success-run --junit-xml junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml

**Comment by petr-balogh** [comment]
```
sed -i 's/ocs_csv_channel:./ocs_csv_channel: "stable-4.9"/' ocs_ci/framework/conf/default_config.yaml
``` should not be needed if you use --ocs-version 4.9 then ocs-ci will load the ocs 4.9 config for you automatically:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml

Basically you should not edit default_config.yaml file at all.

If you need to overwrite some value you can create custom config file with that section/value and pass it via `--ocsci-conf ./path/to/custom/config.yaml`


I don't see rally much details about the failure of the test or what the issue is about?  You do not attach any logs or output from the test case if it's failing and hence no one can help here.

**Comment by achuzhoy** [comment]
I'm not able to see the logs.
Copied the entire directory here: http://file.rdu.redhat.com/~achuzhoy/ocs/ocs-ci_28_apr_2022/
The html report is: http://file.rdu.redhat.com/~achuzhoy/ocs/ocs-ci_28_apr_2022/report.html

How do I retrieve the logs?

**Comment by achuzhoy** [comment]
@petr-balogh were you able to find the needed logs here: http://file.rdu.redhat.com/~achuzhoy/ocs/ocs-ci_28_apr_2022/ ?

If not - Is there any other argument we can add to the executed command[1] to have them?

[1]run-ci tests/ --html report.html -m acceptance --cluster-path /home/kni/ocs-ci/cluster/ --cluster-name spk-factory-0 --ocs-version 4.9 --ocp-version 4.10 --collect-logs --collect-logs-on-success-run --junit-xml junit.xml --ocsci-conf=ocs_ci/framework/conf/default_config.yaml --ocsci-conf=conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml

**Comment by petr-balogh** [comment]
You can create custom config file like my_custom_config.yaml:
```yaml
---
RUN
  log_dir: /path/to/your/logs/dir
```

And provide it to ocs-ci via `--ocsci-conf my_custom_config.yaml`
https://ocs-ci.readthedocs.io/en/latest/readmefiles/conf.README.html#:~:text=log_dir%20%2D%20Directory%20where%20logs%20are%20placed

Than you should have the logs collected to this location, otherwise ocs-ci will write you somewhere at the end of console output where the logs are placed somewhere in /tmp folder .

`--collect-logs --collect-logs-on-success-run` you have correctly set to collect must gather as well, but in your case it's using default /tmp location:
https://github.com/red-hat-storage/ocs-ci/blob/5a3d10353658a07f482321ab7bbc1b4c39df4fcf/ocs_ci/framework/conf/default_config.yaml#L16

Where we crate some folder with RUN_ID of the execution and I agree it's hart to identify so the better to set it via config to custom location.

**Comment by achuzhoy** [comment]
@petr-balogh could you please re-open this one?
