### ISSUE TITLE
 RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/ocs-ci#6222]
@Avilir and I discovered a problem on **existing** ocs-ci setup configured with Python3.9.

After latest rebase, this exception shows up when trying to commit changes:
`git commit -s -m "My Message"`

Exception is:
```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/avili/Testing/OCS-CI/venv/bin/python3.9', '-mvirtualenv', '/home/avili/.cache/pre-commit/repouqv0ppp3/py_env-python3.8', '-p', 'python3.8')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
    
stderr: (none)
Check the log at /home/avili/.cache/pre-commit/pre-commit.log
```

@clacroix12 I couldn't be sure if it is related to the latest version bumps.
But it seems, that specifically on the version upgrade of the hook of black the difference happens.
After locally [modifying this line](https://github.com/red-hat-storage/ocs-ci/blob/master/.pre-commit-config.yaml#L7) back to `python3.7`, things started to work again when we executed `git commit`.

I couldn't be sure about the root cause of this one, and could not figure out a solution yet how to overcome this without downgrading the version.

The only thing that I am a bit suspicious about is the exception `CalledProcessError` which describes clearly a command that was running in a subprocess. And the fact that the `-m` and the `virtualenv` were not separated in the exception is weird to me.

Worth to mention:
`virtualenv --version` result is: `20.15.1`
`python --version` result is: `3.9.13`

**Comment by petr-balogh** [comment]
can you try to do this: `mv /home/avili/.cache/pre-commit /home/avili/.cache/pre-commit.backup`

To check if there is nothing in your cache?

And commit again?

**Comment by Avilir** [comment]
@petr-balogh , this did not help, i got the same error

**Comment by clacroix12** [comment]
@jimdevops19 @Avilir As you've noticed this issue is due you not having the specified python version installed on the system for the hook to use. I set the python version explicitly because that's how they had it in the documentation, however I don't think it's required. If we omit that from the config I believe the hook will use the highest supported python version for the version of the hook we have specified. I will have to test this out but I think that would be an easy change to avoid this issue.

**Comment by clacroix12** [comment]
@jimdevops19 @Avilir As you've noticed this issue is due you not having the specified python version installed on the system for the hook to use. I set the python version explicitly because that's how they had it in the documentation, however I don't think it's required. If we omit that from the config I believe the hook will use the highest supported python version for the version of the hook we have specified. I will have to test this out but I think that would be an easy change to avoid this issue.
