### ISSUE TITLE
Test case .test_must_gather[CEPH] failing in MS provider cluster

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#6412]
The test case given below is failing in Managed Services provider cluster. The check for the file reported in the failure should be skipped.
```
[tests.manage.z_cluster.test_must_gather.TestMustGather.test_must_gather[CEPH]](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/16195/testReport/tests.manage.z_cluster.test_must_gather/TestMustGather/test_must_gather_CEPH_/)
[ Error Details](javascript:hideFailureSummary('id2686645-error'))
Exception: Files don't exist:
[]
Empty files:
[]
Content issues:
['/tmp/tmpgvgwfufm_ocs_logs/ocs_must_gather/quay-io-ocs-dev-ocs-must-gather-sha256-0b7ee7cb95174e08764b06dcb6180bf3c69e499f844e5b6ba21d8d11c5395778/ceph/logs/gather-ceph-fs-clone-debug.log', '/tmp/tmpgvgwfufm_ocs_logs/ocs_must_gather/quay-io-ocs-dev-ocs-must-gather-sha256-0b7ee7cb95174e08764b06dcb6180bf3c69e499f844e5b6ba21d8d11c5395778/ceph/logs/gather-rados ls --pool=ocs-storagecluster-cephblockpool-debug.log']
```

**Comment by abdulkandathil** [comment]
@jilju I have test_must_gather[OTHERS] test failing due to missing file `noobaa-scc-describe.txt`. Should this also be ignored?

```
E           Exception: Files don't exist:
E           ['noobaa-scc-describe.txt']
E           Empty files:
E           []
E           Content issues:
E           []
```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6329/258859/259094/259095/log
Run ID: 1668168070
Test Case: test_must_gather[CEPH]
ODF Build: 4.12.0-100
OCP Version: 4.12
Job name: IBM Cloud IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6048/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003ici3c33-t1/j-003ici3c33-t1_20221111T103742/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6289/256499/256738/256739/log
Run ID: 1668069131
Test Case: test_must_gather[CEPH]
ODF Build: 4.12.0-91
OCP Version: 4.12
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6029/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-060ai3c33-t1/j-060ai3c33-t1_20221110T073408/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6959/290051/290316/290318/log
Run ID: 1669936593
Test Case: test_must_gather
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: RHV IPI 1AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6267/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-011ri1c33-t1/j-011ri1c33-t1_20221201T222122/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6949/289361/289615/289618/log
Run ID: 1669941053
Test Case: test_must_gather
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI KMS VAULT V1 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6276/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-078vukv11cs33-t1/j-078vukv11cs33-t1_20221201T233022/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6942/289052/289298/289300/log
Run ID: 1669937787
Test Case: test_must_gather
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6269/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-016bu1cni30-t1/j-016bu1cni30-t1_20221201T223415/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6782/280211/280449/280451/log
Run ID: 1669734250
Test Case: test_must_gather
ODF Build: 4.12.0-120
OCP Version: 4.13
Job name: AZURE IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6204/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-164zi3c33-uo/j-164zi3c33-uo_20221129T092725/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6773/279533/279783/279785/log
Run ID: 1669717720
Test Case: test_must_gather
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI ENCRYPTION 1AZ RHCOS VSAN LSO VMDK 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6203/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-092vue1cslv33-t1/j-092vue1cslv33-t1_20221129T092854/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6739/277710/277960/277963/log
Run ID: 1669685096
Test Case: test_must_gather
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 UPI FIPS 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6187/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-243vuf1cs33-t1/j-243vuf1cs33-t1_20221129T002117/logs/
Error Message: ```Exception: Files don't exist```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6539/268961/269152/269155/log
Run ID: 1669152584
Test Case: test_must_gather
ODF Build: 4.12.0-114
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6117/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t1/j-001vud1cs33-t1_20221122T193952/logs/
Error Message: ```Exception: Files don't exist```

**Comment by am-agrawa** [comment]
@jilju Do you think someone from MS team can pick it up?

**Comment by am-agrawa** [comment]
@OdedViner Do we have any product bug/open issue to track it for other platforms/configs other than MS?

**Comment by AviadP** [comment]
i dont see this issue anymore
