### ISSUE TITLE
Func get_clusterlogging_subscription returns bool

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#6610]
Function needs to be modified, test_upgrade_logging is failing on the above func with error

        # Matching the OCP version and cluster-Logging version
        ocp_version = get_ocp_version()
        logger.info(f"OCP version {ocp_version}")
        subscription = get_clusterlogging_subscription()

      logging_channel = subscription.get("spec").get("channel")
E           AttributeError: 'bool' object has no attribute 'get'

tests/ecosystem/upgrade/test_logging_upgrade.py:183: AttributeError

**Comment by avd-sagare** [comment]
This testcase is failing because -
1. Before OCP 4.7 the versions of OCP and cluster logging version are moving parallel e.g If OCP 4.5 then logging version will also be 4.5.  So in that case we got to know after OCP upgrade logging is upgraded or not.
Now OCP 4.7 on-words cluster logging version is not following OCP version. So in that case this tc fails to validate as logging channel is different.

**Comment by avd-sagare** [comment]
As per new process of logging upgrade after OCP 4.7, This test case is no longer valid. Creating new test case as per updated process. Hence closing this issue.
