### ISSUE TITLE
Fix the new test "tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py" to OCS label new worker node

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#6688]
Fix the new test "tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py" to OCS label new worker node when we use a non-MS cluster

**Comment by am-agrawa** [comment]
Assigning to Amrita as discussed in Brown Squad sync-up.

**Comment by yitzhak12** [comment]
Okay, thanks. 
@amr1ta if you need my help let me know

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6640/272924/272990/272991/log
Run ID: 1669612560
Test Case: test_rolling_terminate_and_recovery_in_controlled_fashion_ipi
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: VSPHERE6 IPI 1AZ RHCOS VSAN 3M 3W tier4b
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6147/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-026vi1cs33-t4b/j-026vi1cs33-t4b_20221128T040824/logs/
Error Message: ```ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum b,c; 2 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 2 hosts (2 osds) down; 1 rack (2 osds) down; Degraded data redundancy: 1508/4524 objects degraded (33.333%), 150 pgs degraded, 353 pgs undersized```
