### ISSUE TITLE
The image we use when collecting must-gather on IBM is incorrect

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/ocs-ci#6890]
```
Failed during must gather logs! Error: Error during execution of command: oc adm must-gather --image=registry.redhat.io/odf4/ocs-must-gather-rhel8:latest --dest-dir=/tmp/tmpkc91z90m_ocs_logs/ocs_must_gather.
Error is 

Error running must-gather collection:
    gather did not start for pod must-gather-zd4kk: unable to pull image: ImagePullBackOff: Back-off pulling image "registry.redhat.io/odf4/ocs-must-gather-rhel8:latest"
```

We are using registry.redhat.io/odf4/ocs-must-gather-rhel8:latest but we need to use [quay.io/rhceph-dev/ocs-must-gather:latest-4.12](http://quay.io/rhceph-dev/ocs-must-gather:latest-4.12)

**Comment by clacroix12** [comment]
@OdedViner is this an issue with IBM only or is this also happening on other platforms?

**Comment by OdedViner** [comment]
@clacroix12 only on IBM

**Comment by petr-balogh** [comment]
This is because of the ROKS - managed deployment over IBM Cloud.

The change of image is happening here:
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L5702

This is because we cannot use the global pull secret and as a hack we do the update of secret and all Service Accounts for installation of ODF in openshift-storage namespace. The issue with must-gather is that it's creating in diffent NS or create new SA and there is no way how to dynamically change it from what I remember, hence we were using the live must gather image for IBM cloud - or the GAed version of it.

There is maybe one more place where we deal with it for upgrade here:

https://github.com/red-hat-storage/ocs-ci/pull/5839/files#diff-8d2eef2bd4736b8e5f31092474473c3443d93cbad2a9d46c889642f16fd71958R308

So the logic will need to be updated to do it only when it's deployment type managed.
