### ISSUE TITLE
AssertionError: Failed to create pod for: cluster_load

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#7506]
```Message: failed on teardown with "AssertionError: Failed to create pod
assert None"
Type: None


Text:
def finalizer():
        """
        Stop the thread that executed watch_load()
        """
        config.RUN["load_status"] = "finished"
        if thread:
            thread.join()
        if cluster_load_error:



      raise cluster_load_error

tests/conftest.py:1632: 
```
seen here:
 https://url.corp.redhat.com/b7d01ef
and
here: 
https://url.corp.redhat.com/321cc41

**Comment by ebenahar** [comment]
Looks like the failure is on Project creation:

```2023-04-13 11:54:59  08:54:58 - MainThread - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: bg-fio-load-0fd58 of kind: Project, selector: None, Error: Error during execution of command: oc -n bg-fio-load-0fd58 get Project bg-fio-load-0fd58 -n bg-fio-load-0fd58 -o yaml.
2023-04-13 11:54:59  Error is Error from server (NotFound): namespaces "bg-fio-load-0fd58" not found
2023-04-13 11:54:59  
2023-04-13 11:54:59  08:54:58 - MainThread - ocs_ci.ocs.ocp - WARNING  - Number of attempts to get resource reached!
2023-04-13 11:54:59  08:54:58 - MainThread - ocs_ci.ocs.ocp - INFO  - Project bg-fio-load-0fd58 got deleted successfully```

**Comment by ebenahar** [comment]
DeploymentConfig pod creation succeeds:

```
22:03:24 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 create -f /tmp/DeploymentConfigstp2kit2 -o yaml
22:03:24 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 get DeploymentConfig pod-test-rbd-7876af156e3448379be5a48ddd3 -n bg-fio-load-3f5e4 -o yaml
22:03:25 - MainThread - ocs_ci.helpers.helpers - INFO  - pod-test-rbd-7876af156e3448379be5a48ddd3
22:03:25 - MainThread - ocs_ci.ocs.ocp - INFO  - Waiting for a resource(s) of kind pod identified by name 'pod-test-rbd-7876af156e3448379be5a48ddd3-1-deploy' using selector None at column name STATUS to reach desired condition Running
22:03:25 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 get pod pod-test-rbd-7876af156e3448379be5a48ddd3-1-deploy -n bg-fio-load-3f5e4 -o yaml
22:03:26 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 get pod pod-test-rbd-7876af156e3448379be5a48ddd3-1-deploy -n bg-fio-load-3f5e4
22:03:27 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 get pod  -n bg-fio-load-3f5e4 -o yaml
22:03:28 - MainThread - ocs_ci.ocs.ocp - INFO  - status of pod-test-rbd-7876af156e3448379be5a48ddd3-1-deploy at STATUS reached condition!
22:03:28 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-3f5e4 get Pod  -n bg-fio-load-3f5e4 -o yaml
```

The failure is on getting the pod obj in pod_factory_fixture. This is because in https://github.com/red-hat-storage/ocs-ci/blob/9b22c9b2547cb7ee6871e432ed9da73de0458eef/ocs_ci/helpers/helpers.py#L417 we look for pod that doesn't have `"-1-deploy"` in its name and has the newly created pod name. But in the relevant namespace, there are no pods that don't have `"-1-deploy"` in their name, the `create_pod` returns None.

I will continue investigating and particularly, why we expect a pod without `"-1-deploy"` in its name

**Comment by ebenahar** [comment]
Apparently, the deploymentConfig is the resource that doesn't have `"-1-deploy"` in its name. 
I wonder if instead of examining the list of pods, we should not examine the list of deploymentConfigs and return the relevant one.

Removing the condition of:
```python
 if "-1-deploy" not in dpod.name: 
```
solves this and the pod gets created successfully.

@prsurve do you happen to know if there was a change in one of the recent OCP versions that there is no longer pod without `"-1-deploy"` in its name?

**Comment by prsurve** [comment]
@ebenahar i haven't ran any deploymentConfigs workloads recent i can test it and update it here

**Comment by prsurve** [comment]
@ebenahar I tried running the same workload we use on ocs-ci and I see that  only pod `fedorapod-1-deploy` is created, causing failure in the run. I was going over [Openshift doc's suggestion](https://docs.openshift.com/container-platform/4.12/applications/deployments/what-deployments-are.html#deployments-comparing-deploymentconfigs_what-deployments-are) ` it is recommended to use Deployment objects unless you need a specific feature or behavior provided by DeploymentConfig objects. `  we might have to move to Deployment

**Comment by ebenahar** [comment]
`I tried running the same workload we use on ocs-ci and I see that only pod fedorapod-1-deploy is created` - Exactly what I am seeing.

I will try changing the usage of Cluster load to Deployment. 
Thanks a lot Pratik for checking!
