### ISSUE TITLE
Failed to recover a worker node from shutdown operation When using vSphere IPI

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7760]
When shutting down a worker node with vSphere IPI, the node gets stuck in a NotReady state. The worker node is neither started nor removed from the cluster(and then we should expect a new worker node to be created). 
See, for example, the failed test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/25435/testReport/tests.manage.z_cluster.nodes.test_nodes_restart/TestNodesRestart/test_nodes_restart_True_/.
If it's a product bug, we need to raise a new BZ.

**Comment by AviadP** [comment]
Reopening — this recurred on a recent run and matches the exact symptom described above.

**Run**: vSphere IPI, in-transit encryption, 3M/6W, post-upgrade job
**Test**: `test_nodes_restart[True]` ([OCS-894](https://redhat.atlassian.net/browse/OCS-894))
**ODF**: 4.21.9-1 (konflux) / **OCP**: 4.21.0-0.nightly-2026-06-19-050132
**RP**: https://reportportal-ocs4.apps.dno.ocp-hub.prod.psi.redhat.com/ui/#ocs/launches/all/51619/2229088/2229140/log

After `restart_nodes(force=True, wait=False)` restarted all 9 nodes, one worker node's kubelet posted its last heartbeat and never came back — the API server kept a stale `Ready` condition long enough for `wait_for_nodes_status(timeout=420)` to report success, then the node flipped to `Unknown`/`Unreachable` about 2.5 minutes later and stayed that way for at least the next 10 minutes.

Because that node held the only replica for one OSD and one mon (prior pod-to-node placement via PV/PVC), `rook-ceph-osd-2` and `rook-ceph-mon-d` couldn't reschedule anywhere else:

```
FailedScheduling: 0/9 nodes are available: 1 node(s) were unschedulable,
3 node(s) had untolerated taint(s), 5 node(s) didn't match Pod's node
affinity/selector.
```

With the cluster down to 2/3 OSDs and 2/3 mons, `test_nodes_restart[True]`'s `health_check()` call exhausted its retry budget (~9.5 min) and failed with `CephHealthException` (HEALTH_WARN, ~220 undersized PGs). The cluster self-healed roughly 40 minutes later once the node rejoined — no permanent damage, but well outside anything the test waits for.

This is the same "node neither started nor removed from the cluster" behavior originally reported here in 2023, still reproducing on 4.21 in 2026 with no fix or workaround merged in the meantime.

**Comment by AviadP** [comment]
i would say that this is not an automation issue. one node failed to recover, OSD have hard affinity to this node, ceph cant recover. its vm issue or kublet failure. closing this, its an infrastructure issue, and out of the scope for ocs-ci automation code
