### ISSUE TITLE
Deployment constantly fails during must-gather logs collection

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#865]
Deployment constantly fails for me (3/3). Happens during the execution of this command, which hangs for more than 10 minutes:

22:27:32 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ebenahar/ebenahar-ocs-dir/auth/kubeconfig adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather --dest-dir=/tmp/failed_testcase_ocs_logs_1570214678/deployment_ocs_logs/ocs_must_gather

Access to http://pkgs.devel.redhat.com/cgit/containers/ocs-registry/plain/deploy-with-olm.yaml?h=ocs-4.2-rhel-8 is successful though

==========
Snippent:

E           requests.exceptions.ConnectionError: HTTPConnectionPool(host='pkgs.devel.redhat.com', port=80): Max retries exceeded with url: /cgit/containers/ocs-registry/plain/deploy-with-olm.yaml?h=ocs-4.2-rhel-8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f008f3fa780>: Failed to establish a new connection: [Errno -2] Name or service not known'))

ocs-venv/lib64/python3.7/site-packages/requests/adapters.py:516: ConnectionError

=============
full stack traceback:
http://pastebin.test.redhat.com/803357

=============
git log:

commit e9f673f5f2cd0ee6f0cdab9325b3d04b5aa6617d (HEAD, ocs-ci/master, ebenahar/master)
Author: Petr Balogh <petr-balogh@users.noreply.github.com>
Date:   Fri Oct 4 14:46:12 2019 +0200

    Move to downstream (#839)
    
    * Move to downstream
    
    Fixes: #818
    
    Signed-off-by: Petr Balogh <pbalogh@redhat.com>

**Comment by petr-balogh** [comment]
Hey @ebenahar  ,  have you been connected to VPN that time as the file we consuming for deploy DS build is in internal RH network? I haven't seen this issue today even last week. Thanks

**Comment by mbukatov** [comment]
Looking at the log, I see that:

* The test run failed during deployment because it couldn't download `deploy-with-olm.yaml` file from internal server.
* The internal server hosting `deploy-with-olm.yaml` file was not accessible from the machine where the test was executed from while the deployment was running.
* This failure of cluster deployment triggered a must gather run (as any other failure would).
* There is no evidence that ocs must-gather run failed in any way. That said, I don't expect the ocs must gather run was usefull either, because ocs wasn't installed at all, so there was hardly any evidence to collect.

Since the error reported is `Name or service not known`, I would suggest to check network configuration of the machine where the test was run. I don't think there anything to fix in ocs-ci.

**Comment by petr-balogh** [comment]
Closing the issue, if you still see some issue, feel free to reopen

**Comment by ebenahar** [comment]
Thanks Petr and Martin for looking into this. I wasn't connected via VPN. Ack for closing the issue
