### ISSUE TITLE
Skip reporting fixture failure in html report as separate test

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#879]
Current html reports fixture failure in separate row which is confused by many as new test, we should report test only have polarion id and skip additional fixtures that show up in the rows.

**Comment by vasukulkarni** [comment]
Eg: below which are unnecessary 

```
Error | tests/e2e/logging/test_openshift-logging.py::Test_openshift_logging_on_ocs::test_create_new_project_to_verify_logging::teardown | This function creates new project to verify logging in EFK stack 1. Creates new project 2. Creates PVC 3. Creates Deployment pod in the new_project and run-io on the app pod 4. Logs into the EFK stack and check for new_project 5. And checks for the file_count in the new_project in EFK stack | 211.38
-- | -- | -- | --

Error | tests/manage/pv_services/test_create_storage_class_pvc.py::TestOSCBasics::test_basics_cephfs::teardown | Testing basics: secret creation, storage class creation, pvc and pod with cephfs | 31.11

Skipped | tests/manage/cluster/nodes/test_nodes_maintenance.py::TestNodesMaintenance::test_node_maintenance[worker]::setup | OCS-1269/OCS-1272: - Maintenance (mark as unscheduable and drain) 1 worker/master node - Check cluster functionality by creating resources (pools, storageclasses, PVCs, pods - both CephFS and RBD) - Mark the node as scheduable - Check cluster and Ceph health | 0.59

Skipped | tests/manage/cluster/nodes/test_nodes_maintenance.py::TestNodesMaintenance::test_node_maintenance[master]::setup | OCS-1269/OCS-1272: - Maintenance (mark as unscheduable and drain) 1 worker/master node - Check cluster functionality by creating resources (pools, storageclasses, PVCs, pods - both CephFS and RBD) - Mark the node as scheduable - Check cluster and Ceph health

```

**Comment by petr-balogh** [comment]
Not sure I follow.  Let's bring it on automation mtg if you can explain better to me what is the issue here.  Can you point to some specific mail thread where do you see this so it will give me more context about it when I will see it as a whole? Or do the screenshot and attach it here?

**Comment by clacroix12** [comment]
@petr-balogh see the following images from the latest email report. The first is the teardown (ERROR) and the second is the actual test (PASSED). 

![Screen Shot 2019-10-10 at 8 25 20 AM](https://user-images.githubusercontent.com/1605721/66583234-d6252d00-eb37-11e9-9791-094adbb55c8b.png)
![Screen Shot 2019-10-10 at 8 25 45 AM](https://user-images.githubusercontent.com/1605721/66583242-d7eef080-eb37-11e9-8921-aebb49019c85.png)

I'm not sure that having the setup/teardown as their own items is unnecessary in cases like this. We have a test that is passing however we have an error occurring in the teardown which we should acknowledge and address. If we don't have the setup/teardown entries in our report I'm afraid that we will lose sight of things like this.

**Comment by vasukulkarni** [comment]
@clacroix12 @petr-balogh what the issue is asking for is to report test cases as one row(the test case can have setup/teardown and many other markers and if any one those fail the testcase itself should be marked as fail and the logs will tell where it failed)

From user point of view, we just have to know what polarion test id has failed and for folks who dont want to debug(dev/others), they can just point out exact test case that failed without having to understand our internal details of what setup/teardown/etc has failed.

**Comment by petr-balogh** [comment]
@vasukulkarni we discussed this with @vavuthu on our 1:1 and agreed on:
The way how we make the report now is pytest way of providing report which is broadly used in the community and for the ppl who are using the pytest expect this behavior of distinguish between failures and errors . So pytests reports separately those errors, failures as it's designed and in case of `Error` in setup/teardown pytest reports those as we do in our HTML report as well.

For user if they know what how the pytest reports it's quite easy to understand from the report where the test is failing and in case we failed in `Setup` we know that most likely the `Teardown` will fail as well and it's not confusing to see this Error in the report if the user understand the way how pytest reports the results (different between Error/Failure). 

In case we start modifying the HTML report we need to change the logic of how pytest is reporting those defects which as we agreed with Vijay is probably not the way we want to go as is something which pytest does for everyone and it's documented.

So rather than change the logic we can educate the users and maybe document this somehow better.  

Another point of view that we can add the another line to the report which where we will count real pass rate with skips, pass rate without skips counted from number of the exact failed test cases no matter if it failed in setup/test itself/teardown. 

@vavuthu please add you thoughts and the spreadsheet you linked to me on 1:1 and in case I missed something please correct me.  

I suggest maybe before decide some other behavior and changes to our reporting to bring this to mailing list ocs-qe and rhocs-eng, with link to this issue with bringing all the ideas and pros and cons why to change the logic how pytest reports and if ppl think that we should change the logic of native behavior of pytest.

Thanks

**Comment by vavuthu** [comment]
> @petr-balogh see the following images from the latest email report. The first is the teardown (ERROR) and the second is the actual test (PASSED).
> 
> ![Screen Shot 2019-10-10 at 8 25 20 AM](https://user-images.githubusercontent.com/1605721/66583234-d6252d00-eb37-11e9-9791-094adbb55c8b.png)
> ![Screen Shot 2019-10-10 at 8 25 45 AM](https://user-images.githubusercontent.com/1605721/66583242-d7eef080-eb37-11e9-8921-aebb49019c85.png)
> 
> I'm not sure that having the setup/teardown as their own items is unnecessary in cases like this. We have a test that is passing however we have an error occurring in the teardown which we should acknowledge and address. If we don't have the setup/teardown entries in our report I'm afraid that we will lose sight of things like this. We might also consider the case where setup fails/errors and the test is skipped entirely.
> 
Agreed. The one we are sending the reports is the main visualization for the Team. Based on the reports, team will investigate the failures/Errors. If we surpass the result summary or skip the fixture failures in reports, it will be like underlying issues where non one knows unless someone goes to jenkin jobs and see the failures.

Another issue is, even though if we don't show the fixture failures in reports table, In Summary it shows everything like below

Summary
26 tests ran in 5081.25 seconds.

26 passed, 9 skipped, 0 failed, 2 errors, 0 expected failures, 0 unexpected passes

which again leads to inconsistency between "Summary" and "Results Table"

> In cases like @vasukulkarni pointed out where the test is skipped but the teardown errors or fails, I think this is a different issue where that particular teardown isn't robust enough to handle the case where the test doesn't execute. We should file an issue for that teardown specifically and ensure it can essentially handle a skipped or partially executed test case. If our teardowns are more robust, we should see fewer instances of what vasu is seeing.

If a test case is skipped, pytest never runs teardown/testcase. In Reports we will see only skipped but not teardown.  I think the main concern is teardown Errors. I am not sure if anyone raises issue for the teardown Errors and start investigating the errors.

Scenarios Tested with sample test case and comments:

https://docs.google.com/spreadsheets/d/191dJoccGsTViXMoyZDLkw0LShQvYfpYJHmR86-hDUQA/edit?pli=1#gid=0

**Comment by vasukulkarni** [comment]
I think it is better to discuss this one in call, IMHO If pyhtml reporting doesn't meet, I guess one could write own custom module to meet our requirements,  and using jinja2 templating I think it will hardly cross 100 lines of code.

**Comment by vasukulkarni** [comment]
Closing based on discussion.
