### ISSUE TITLE
Add ascii table format results at the end of the execution

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#881]
To make it better for developers to debug and report issue on what test cases failed, add ascii table at the end of the results and report test failures with polarion ids.

**Comment by clacroix12** [comment]
Pytest provides something like this:

```
  -r chars              show extra test summary info as specified by chars:
                        (f)ailed, (E)rror, (s)kipped, (x)failed, (X)passed,
                        (p)assed, (P)assed with output, (a)ll except passed
                        (p/P), or (A)ll. (w)arnings are enabled by default
                        (see --disable-warnings).
```

I didn't want to hardcode this in our `pytest.ini` because if users want to utilize this but change the value we are passing I believe it will conflict. However, setting this up from the jenkins side is trivial and doesn't conflict with manual executions. In fact you can already pass this in the `ADDITIONAL_PYTEST_PARAMS` section of the form.

I know this doesn't handle the Polarion side of things but it's something that can help with summarizing the results while we figure that out.

**Comment by petr-balogh** [comment]
I also pointed in the email now:

I think we already have HTML report implemented in the ocs-ci. You can also see usage documentation here: https://github.com/red-hat-storage/ocs-ci/blob/master/docs/usage.md#additional-arguments
Talking about those two params:

--html - to generate html reports of the test run
--self-contained-html - creates self-contained html file containing all necessary styles and scripts
I think this was implemented by Vijay so he can help with it as well.
But basically you can generate the HTML report which will be more readable. 

Also there are tools which allow you to generate some nice html report from xunit file. 

E.g this one:  https://github.com/Zir0-93/xunit-to-html

So as pytest at the end of the execution generate the xunit file so you can take it and generate such report from it via some tool which will show you the information as we have in jenkins.

So isn't the html report we currently have enough?

**Comment by vavuthu** [comment]
Closing this issue as we have updated the reporting multiple times over period of time.

Please feel free to open new issue if needed
