### ISSUE TITLE
Use wait_for module instead of implementing wait functions

### ISSUE THREAD

**Issue by ebondare** [red-hat-storage/ocs-ci#93]
Currently we have two functions that do waiting for a certain condition: wait_for_resource_status and wait_for_func_status. Wouldn't it be nicer to use https://pypi.org/project/wait_for/ instead?

**Comment by ebenahar** [comment]
This issue was encountered once again. Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7100/296186/296193/296197/log
Run ID: 1670263326
Test Case: test_validate_ceph_config_values_in_rook_config_override
Error Message: AssertionError: The Ceph config, set by rook-config-override is different than the expected. Please inform OCS-QE about this discrepancy. The expected values ar
