### ISSUE TITLE
measure_pvc_creation_time Needs enahancement

### ISSUE THREAD

**Issue by ramkiperiy** [red-hat-storage/ocs-ci#988]
measure_pvc_creation_time function is failing, if we try to measure time for 500+ pvc's.
Either this function needs enhancement or need a new function in-case of more than 500+ PVC's

**Comment by Akarsha-rai** [comment]
And also we need to update the code to pick the right provisioner plugin. 
We have two provisioner plugins out of which one is active and other act as idle.

In code we are selecting only the first plugin:
```
ceph_pod = Pod(**rbd_provision_pod_items[0])
    return ceph_pod
```

**Comment by gklein** [comment]
> measure_pvc_creation_time function is failing, if we try to measure time for 500+ pvc's.
> Either this function needs enhancement or need a new function in-case of more than 500+ PVC's

As a best practice, I think we need to reuse the same function in order to eliminate code duplication. It would be better if we can fix it or add extra parameters to function in order to support this "special case".

Could you please share some more details about the failure. What's the exception you are receiving when running with 500+ PVCs?

**Comment by ramkiperiy** [comment]
Closing this Issue, since code is merged.
