### ISSUE TITLE
`test_debug_verbosity_of_ceph_components[mds-crush]` fails as binary missing

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#9984]
Test : `tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py::TestDebugVerbosityOfCephComponents::test_debug_verbosity_of_ceph_components[mds-crush]`

Description: The test fails with the below error as the binary is unavailable in the expected location.

```
E               FileNotFoundError: [Errno 2] No such file or directory: '/home/automation/ocs-ci/data/odf-cli'
```

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/335/22320/1067317/1067492/log?item1Params=filter.cnt.name%3Dtest_debug_verbosity_of_ceph_components%26page.page%3D1&logParams=history%3D1059082%26page.page%3D1

**Comment by shrinivas-sidral** [comment]
**test_debug_verbosity_of_ceph_components fail due to the binary missing on ODF version 4.16.1**

Tests: `tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py::TestDebugVerbosityOfCephComponents::test_debug_verbosity_of_ceph_components[mds-crush]`
`tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py::TestDebugVerbosityOfCephComponents::test_debug_verbosity_of_ceph_components[osd-crush]`
`tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py::TestDebugVerbosityOfCephComponents::test_debug_verbosity_of_ceph_components[mon-crush]`

Description: The test fails with the below error as the binary is unavailable in the expected location.

>              FileNotFoundError: [Errno 2] No such file or directory: '/home/automation/ocs-ci/data/odf-cli'


[test_debug_verbosity_of_ceph_components[mds-crush].log](https://github.com/user-attachments/files/16412284/test_debug_verbosity_of_ceph_components.mds-crush.log)
[test_debug_verbosity_of_ceph_components[mon-crush].log](https://github.com/user-attachments/files/16412289/test_debug_verbosity_of_ceph_components.mon-crush.log)
[test_debug_verbosity_of_ceph_components[osd-crush].log](https://github.com/user-attachments/files/16412290/test_debug_verbosity_of_ceph_components.osd-crush.log)
